- kernel-rs/src/console.rs
- kernel-rs/src/uart.rs
위 그림과 같이 Clippy 오류가 발생하는 것을 해결했습니다.
> Clippy  : Uart::new -> Uart::init

- kernel-rs/src/console.rs
- kernel-rs/src/kernel_main.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- make / usertests / hart message / fmt
- 기존에 PROC으로 나타내던 Process들의 pool을 ProcessPool type으로 변경하고 global PROCPOOL을 선언.
- 해당하는 함수들을 ProcessPool의 method로 implement
@efenniht 
- wait의 경우 Proc을 refactoring 하면서 조금 더 생각해봐야 할 것 같습니다.
- 이어서 Proc, CpuPool, Cpu, Context 등에 대한 수정을 진행하도록 하겠습니다.
> [subissue of #204] Create ProcessPool & implement methods.

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/riscv.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/vm.rs
- all usertest passed
- cargo fmt done
---
- subissue of #195
- vm.rs의 포인터로 되어 있는 `KERNEL_PAGETABLE`을 `PageTableEntry`, `RawPageTable`, `PageTable` struct의 구조로 재구성하였습니다.
---
1. 현재 temp로 되어 있는 `walk_temp`와 같은 함수들을 'walk'대신 사용할 수 있도록 다른 파일에도 수정된 struct 적용
2. 가능한 함수들을 각 struct의 method로 수정
한 후에 merge 가능한 pr로 돌리겠습니다.
> Refactor vm.rs - pagetable struct

- .travis.yml
- Makefile
- kernel-rs/src/console.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/memlayout.rs
- kernel-rs/src/poweroff.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/virtio_disk.rs
- kernel-rs/src/vm.rs
- kernel/syscall.h
- user/init.c
- user/user.h
- user/usertests.c
- user/usys.pl
Closes #17 
Travis CI 를 이용하여 PR 이 머지되기 전에 자동으로 1) formatting 이 되었는 지, 2) clippy 오류가 없는 지, 3) usertests가 성공적으로 작동하는 지 테스트합니다. 이를 위해:
- 현재 테스트 환경 (QEMU virt device) 에서 poweroff 를 하는 함수와 시스템 콜을 추가했습니다.
- `init` 이 `sh` 를 실행할 지 `usertests` 를 실행할 지 컴파일 타임에 결정할 수 있게 만들었습니다.
- `init` 이 `usertests` 를 실행하는 경우 테스트가 종료하는 대로 poweroff를 하여 timeout 이 나지 않고 성공하도록 합니다.
Travis CI free-tier 는 cpu가 느려서, debug profile로 테스트하는 경우 timeout 이 납니다. 그래서 release profile 로 테스트하도록 설정했습니다.
이 PR 을 머지하시고 @jeehoonkang 교수님께서 Travis 를 연동해 주시면 이후 PR 에서 사용할 수 있습니다.
> Turn on Travis CI

- kernel-rs/src/sleeplock.rs
- kernel-rs/src/spinlock.rs
`Sleeplock`과 `Spinlock` 에 `get_mut` 과 `get_mut_unchecked` 를 추가합니다.
- `get_mut` 은 해당 락을 가리키는 레퍼런스가 유일할 때 락을 걸지 않고 내부 data를 mutable하게 빌릴 수 있습니다.
- `get_mut_unchecked` 는 일반적으로 사용하면 안 되지만, 리팩토링 중간 과정에서 유용하게 쓸 수 있습니다: lock으로 보호하는 부분과 보호하지 않는 부분을 나누는 리팩토링을 할 때, 락을 걸지 않고 inner를 접근하는 코드가 있을 수 있습니다. 그 경우 먼저 `get_mut_unchecked` 를 사용하여 (비록 unsafe 하더라도) 최소한의 수정으로 테스트 가능한 커밋을 만들고, 추후에 올바르게 코드를 수정하여 급격한 코드 변화로 인한 디버깅 비용을 줄일 수 있습니다. (cc @kimjungwow @coolofficials)
메서드만 추가하는 것이므로 바로 머지하겠습니다.
> Add helper functions in Spinlock and Sleeplock.

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/kernel_main.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/stat.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/virtio_disk.rs
- 아래와 같이 struct Inode를 리팩토링했습니다. 이유는
- Inode의 Sleeplock이 보호하는 대상을 명확히 하고
- Inode의 Sleeplock을 쥔 상태에서 호출되는 함수는 `impl InodeGuard<'_>`에서 다루기 위함입니다.
```Rust
pub struct InodeGuard<'a> {
guard: SleepLockGuard<'a, InodeInner>,
pub ptr: &'a Inode,
}
pub struct InodeInner {
/// inode has been read from disk?
pub valid: bool,
/// copy of disk inode
pub typ: i16,
pub major: u16,
pub minor: u16,
pub nlink: i16,
pub size: u32,
pub addrs: [u32; 13],
}
/// in-memory copy of an inode
pub struct Inode {
/// Device number
pub dev: u32,
/// Inode number
pub inum: u32,
/// Reference count
pub ref_0: i32,
// pub inner: InodeInner,
pub inner: SleeplockWIP<InodeInner>,
}
```
- `Buf`의 Sleeplock도 SleeplockWIP로 변경? (우선순위 고민)
> Use SleeplockWIP<Inode> (related to #218)

- kernel-rs/src/file.rs
- kernel-rs/src/sysfile.rs
- Closes #218 
- https://github.com/kaist-cp/rv6/pull/211#discussion_r489970751 에서 언급되었듯, `File::read(), write(), stat()`가 `&mut self` 를 받는 것은 실제 의미와 다릅니다. 
(&mut self 는 File 에 대한 접근을 할 때 다른 스레드에서는 File 에 접근할 수 없다는 뜻인데, File 자체에 걸린 락이 없어서 그렇게 되지는 않습니다.)
- https://github.com/kaist-cp/rv6/issues/218#issue-705237761 에서는 `Inode` 의 lock 을 건 상태에서만 `off` 를 접근할 수 있는 타입을 말씀해주셨습니다. 
그런데 이 타입의 목적이 `File::read(), write(), stat()`이 `&mut self`가 아닌 `&self`을 받도록 하기 위함이면 FileType::Inode::Off의 타입을 u32에서 Cell<u32>로 바꿔도 괜찮을까요? 
**여러 개의 파일이 동시에 한 Inode를 가리킬 수 있어서 off 를 inode 에 집어넣을 수 없기 때문에, 저는 Inode의 lock을 쥐어야지만 off를 수정할 수 있음을 명시적으로 나타낼 필요는 없다고 판단했습니다.** 
물론 `File::read(), write()` 코드에서는 Inode의 lock을 먼저 쥔 뒤 `InodeGuard::read, write()`를 실행하고, off를 수정한 뒤, Inode의 lock을 drop합니다.
> [Closes #218] Make FileType::Inode::Off Cell

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/vm.rs
#256 에서 update(rebased).
@efenniht 
`ExecutionGuard`의 implementation은 새 issue (#258) 를 만들어 다음 PR에서 진행하겠습니다.
[Major patch]
`struct Proc`의 남은 field들을 `UnsafeCell<ProcData>`로 wrap했습니다.
- 내용 관련하여 Stacked Borrows(https://plv.mpi-sws.org/rustbelt/stacked-borrows/paper.pdf) 를 참조하면 좋습니다.
- `name`은 `creation, exit`에서만 변경되어 `UnsafeCell`로 묶지 않았습니다.
[Minor patch]
`struct ProcInner`와 `struct Proc`의 `field inner`를 각각 `struct ProcInfo`와 `info`로 변경했습니다.
> [subissue for #214] Implement ProcData

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/vm.rs
- closes #226 
---
수정한 내용입니다.
- `VAddr`의 `copyin` `dst`에서 `&mut [u8]`을 인자로 받도록 수정
- `copyin`, `copyinstr`의 `dst`에서 `&mut [u8]`을 인자로 받도록 수정
- `copyout`의 `src`에서 `&[u8]`을 인자로 받도록 수정
> [Closes #226] copyin, copyout 함수 인자로 &[u8] 적용

- kernel-rs/src/sysfile.rs
**raw pointer를 리턴하는 함수들을 reference를 리턴하도록 바꾸면 unsafe lines를 줄일 수 있을 것 같아** 이와 같이 수정했습니다.  
다른 함수들도 비슷한 수정을 할 수 있을 것 같은데 (mut이 필요 없는데 raw pointer를 리턴하는 경우), 올바른 방향인지 확인하고자 작은 수정이지만 PR 올립니다.
> [Unsafe 줄이기] argfd returns not *mut RcFile but &'a RcFile

- Makefile
- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/fcntl.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/memlayout.rs
- kernel-rs/src/plic.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/uart.rs
- kernel-rs/src/virtio.rs
- kernel-rs/src/virtio_disk.rs
- kernel/console.c
- kernel/defs.h
- kernel/exec.c
- kernel/fcntl.h
- kernel/fs.c
- kernel/memlayout.h
- kernel/plic.c
- kernel/proc.c
- kernel/proc.h
- kernel/syscall.c
- kernel/sysfile.c
- kernel/trap.c
- kernel/uart.c
- kernel/virtio_disk.c
- user/sh.c
- user/usertests.c
- **추가로 uart.rs 관련 변경점이 많아 상욱님께도 리뷰 요청 드리겠습니다** : https://github.com/kaist-cp/rv6/commit/8a23e0fdd2846f56d1c48de163abe5f66c587f9f
- 2020/4/19 ~ 2020/7/20 까지의 커밋을 반영했습니다.  
- related to #261 
  - `virtio_disk.c::virtio_disk_intr()`에서 `VIRTIO_MMIO_INTERRUPT_ACK`에 `VIRTIO_MMIO_INTERRUPT_STATUS & 0X3`을 넣는 코드를 추가함
  - Rust 반영 완료
    - `virtio.rs`의 `enum MmioRegs`에 `InterruptStatus, InterruptAck` 재생성 완료
    - `virtio_disk.rs::virtio_intr()`에 `MmioRegs::InterruptAck.write(MmioRegs::InterruptStatus.read() & 0x3);` 추가 완료
  - `itrunc()` 함수 관련 변경 사항들
    - 주석 변경 -> Rust 반영 완료
    - `sys_open()`에서도 `itrunc()` 실행 -> Rust 반영 완료
  - `readi()` 관련 변경 사항
    - -1가 아닌 0 리턴 -> Rust 반영 완료
  - `Makefile`에서 `QEMUEXTRA`제거 + `QEMUOPTS` 내용 추가 -> Rust 변경 사항 X
  - `struct proc`의 `tf` 필드명을 `trapframe`으로 변경 : Rust 코드 …
> Merge mit pdos [3] (related to #261)

- kernel-rs/src/bio.rs
- kernel-rs/src/console.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/log.rs
- kernel-rs/src/virtio_disk.rs
- Related to #271 
- `Buf::write()`
- **buf를 disk를 쓰는 주체는 Disk로 판단**하고, `Buf::write()`가 아닌 `virtio_disk_rw()`를 직접 사용하도록 바꾸었습니다.
- `Buf::lock()`와 `Buf::new()`
- **블록의 가장 최신 내용을 읽어오는 행위의 주체 역시 Disk로 판단**했습니다. 따라서 기존 `Buf::new()`의 역할을 `virtio_get_buf()`가 하도록 바꾸었습니다.
- `Buf::lock()` 내부에서 buf.inner.valid가 false인 경우 Disk로 부터 읽어오는 (`virtio_disk_rw()`) 과정이 있었습니다. 이를 `virtio_get_buf()` 내부에서 대신합니다.
- **따라서 `virtio_get_buf()`가 아닌 `Buf::lock()`을 사용하는 경우, Buf에 담긴 내용이 가장 최신의 내용임이 보장되지 않습니다.** 현재 `Buf::lock()`을 사용하는 경우는 `log.rs::install_trans()`의 `let mut dbuf = dbuf.lock();` 한 곳인데, 이 때 `dbuf`는 `ptr::copy`에 의해 다른 내용으로 덮어쓰여져서 문제가 없습니다.
> Remove Buf -> Disk dependency (related to #271)

- README-rv6.md
- Specify qemu version 
- 2020/11/26 기준 우분투 20.04에서 qemu-system-misc 1:4.2-3ubuntu6 보다 더 최신 버전인 6.9, 6.6에서는 부팅이 여전히 되지 않습니다. 계속 6을 사용해야 할 것 같습니다.
- #160 에서 해결했지만, 문서에 적혀있지 않아 추가했습니다.
- Erase cargo-xbuild
- https://github.com/kaist-cp/rv6/commit/de88805673d2886ca81b39602870df7ad83ea205 이후로 cargo xbuild는 사용되지 않아 지웠습니다.
> Update README-rv6.md : specify qemu version and erase cargo-xbuild

- .gdbinit.tmpl-riscv
- kernel-rs/src/console.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/uart.rs
- kernel-rs/src/vm.rs
- kernel/console.c
- kernel/defs.h
- kernel/file.c
- kernel/fs.c
- kernel/log.c
- kernel/pipe.c
- kernel/proc.c
- kernel/proc.h
- kernel/uart.c
- kernel/vm.c
- user/grind.c
- user/usertests.c
- closes #261 
**2020/10/8**
- `.gdbinit.tmpl-riscv` 변경 : Rust는 해당 사항 없음
**2020/10/15**
- `proc.c::procinit()`에서는 각 proc의 `kstack`만 빼고, 이외의 내용을 `proc.c::proc_mapstacks()`에서 담당 -> rv6는 https://github.com/kaist-cp/rv6/commit/fd20c80d7483d4fc1a2c1bd88a7710b29ab82eef 에서 비슷한 역할의 `palloc()`을 만들어 놓았었습니다.
- 함수명을 바꿨습니다. (`palloc()` -> `proc_mapstacks()`)
- `impl ProcData` 밖으로 빼내고, 불필요한 인자 `i`를 없앴습니다.
- `vm.c::kvmmap()`의 첫 인자를 uint64에서 pagetable_t로 변경 -> rv6에서는 이미 `kvmmap()`이 `impl PageTable<KVAddr>` 안에 있어서, 적용할 내용이 없습니다.
- void를 리턴하는 `vm.c::kvminit()`을 pagetable_t를 리턴하는 `vm.c::kvmmake()`로 바꾸고 + 새로 만든 `vm.c::kvminit()`에서는 `kernel_pagetable = kvmmake()`를 실행합니다.
- **rv6에서는 `kvmmake()`가 `PageTable<KVAddr>`이 아닌 void를 리턴하는 것이 좋다고 판단했습니다.** 
- `Kernel::zero()`에서 `page_table: PageTable::zero()`를 이미 실행하기 …
> [Closes #261] Merge mit pdos [8]

- kernel-rs/src/bio.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/fs/superblock.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/virtio_disk.rs
- #306 이어서
- 지저분한 tag가 있었는데 모두 없앴습니다.
- kernel()을 되도록 적게 사용하자는 제안과 관련이 있습니다. kernel()이 사용되는 지점을 점점 더 상위 레벨로 올려서 나중에는 없에버리는게 목표입니다.
- array_const_fn_init에서는 magic number만 사용 가능해서, 일부 리뷰는 반영하지 못했습니다. #309 이슈 생성했고, 코멘트로도 적어두었습니다.
- 나머지 리뷰는 모두 반영하였습니다.
> Remove tag (#306 이어서)

- count_unsafe.py
`cargo-count` 에는 `unsafe` 로 시작하는 문장을 생략하는 버그 (https://github.com/kbknapp/cargo-count/issues/38) 가 있어서, 다른 도구를 새로 만들었습니다. (https://github.com/efenniht/count-unsafe)
rv6 의 경우 unsafe line 은 41.7% 입니다.
```
kernel-rs/src/sysfile.rs : 314/336 = 93
kernel-rs/src/sysproc.rs : 45/54 = 83
kernel-rs/src/virtio.rs : 6/76 = 7
kernel-rs/src/memlayout.rs : 0/34 = 0
kernel-rs/src/start.rs : 34/57 = 59
kernel-rs/src/riscv.rs : 154/275 = 56
kernel-rs/src/trap.rs : 122/142 = 85
kernel-rs/src/sleepablelock.rs : 13/73 = 17
kernel-rs/src/uart.rs : 11/155 = 7
kernel-rs/src/syscall.rs : 87/97 = 89
kernel-rs/src/utils.rs : 0/7 = 0
kernel-rs/src/etrace.rs : 0/117 = 0
kernel-rs/src/plic.rs : 18/22 = 81
kernel-rs/src/vm.rs : 333/508 = 65
kernel-rs/src/fcntl.rs : 0/9 = 0
kernel-rs/src/param.rs : 0/15 = 0 …
```
> Fix: don't use cargo-count.

- README-rv6.md
- kernel-rs/src/plic.rs
- kernel-rs/src/trap.rs
#160 의 root cause를 해결합니다: PLIC MMIO 를 접근할 때 32bit 단위로 접근하도록 수정합니다. 이제 qemu의 최신 버전에서도 정상적으로 작동합니다.
[PLIC spec](https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic.adoc) 과 xv6 구현 모두 해당 영역을 32bit 단위로 접근합니다. Rust로 옮기면서 해당 버그가 introduce 된 것 같습니다.
> Fix: access PLIC in 32-bit.

- .travis.yml
- kernel-rs/src/poweroff.rs
CI 설정을 업데이트합니다.
- bors 가 생성하는 `staging.tmp` 브랜치에 대한 CI 를 스킵합니다. (이것 때문에 많은 PR 이 성공하는데도 실패로 표기되었습니다)
- #320 에 따라 테스트에 사용하는 qemu 버전을 최신을 사용하도록 합니다.
- language 를 minimal로 설정합니다. 설정하지 않은 경우 기본으로 ruby 를 사용하더군요.
- `poweroff.rs` 도 32bit 크기로 접근하도록 수정했습니다.
> Update CI setting

- kernel-rs/src/bio.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sleepablelock.rs
- kernel-rs/src/spinlock.rs
* Closes https://github.com/kaist-cp/rv6/issues/300
* 현재 @anemoneflower 님께서 이미 procGuard관련 refactoring을 하시는걸로 알고 있어서, 최대한 겹치지 않게 parent field 관련된 부분만 한번 시험적으로 변경해봤습니다.
* parent field만을 위한 type 및 API를 만들려다가, 최대한 깔끔하게 하기 위해서 **Spinlock과 매우 비슷한 GlobalSpinlock을 만들었습니다.**
* GlobalSpinlock은 Spinlock과 거의 비슷하나(거의 대부분의 코드를 복사 붙여넣었습니다), 유일한 차이점은 Spinlock은 Spinlock 하나당 RawSpinlock하나를 own하지만, **GlobalSpinlock은 RawSpinlock을 own하지 않고 외부의 global한 RawSpinlock을 가르키는 raw pointer를 갖습니다.**
* **GlobalSpinlockGuard**를 얻기 위해서는 **GlobalSpinlock::lock()** 를 하거나, 동일한 RawSpinlock을 이용하는 다른 GlobalSpinlock으로부터 이미 획득한 GlobalSpinlockGuard를 이용하여 **GlobalSpinlock::lock_with_guard()** 를 하면 됩니다. (spinlock.rs 참고). 굳이 atomic instruction을 다시할 필요가 없도록 하기 위해 이런 API를 추가했습니다.
* ProcInfo의 **parent field**를 Proc안으로 옮긴 후, access하기 …
> [Closes #300] GlobalSpinlock: Acquire global lock "wait_lock" before accessing parent field

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/virtio_disk.rs
- `Disk`를 `FileSystem`으로 옮겼습니다.
- `Disk`를 처음부터 `KERNEL.file_system`에 정의하고, `fsinit()`에서 `Superblock`과 `Log`를 initialize합니다.
> [Minor issue of #271] Move disk to filesystem

- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
* `bmap`과 `bmap_or_alloc`을 공통으로 처리하기 위해 `bmap`의 첫 인자를 `&self`에서 다시 `&mut self`로 바꾸었습니다. 이에 따라 `read`또한 `&mut self`를 받습니다.
* #293 에서는 Cursor 사용을 제안했지만, 그렇게 하면 cursor가 `InodeGuard`를 참조하면서 동시에 그 내부를 mutable하게 참조할 수 있어야 해서 cursor를 사용하는 대신 `bmap_inner`라는 메서드를 만들고 `bmap`과 `bmap_or_alloc`이 모두 `bmap_inner`를 호출하게 변경했습니다.
* #292 이전의 코드는 `read`가 immutable하다는 것과 buf를 새로 할당하지 않는다는 것 모두를 나타낼 수 없었고, #292 를 통해 둘 모두를 표현하게 되었습니다. 이 PR은 `read`가 immutable함을 표현하지는 못하지만 buf를 새로 할당하지 않는다는 것을 명시적으로 드러내는 것은 유지합니다. 이로써 코드가 조금 짧아지기는 했으나 이 수정이 좋은 방향인지는 모르겠습니다.
> [#293] bmap_inner: common part of bmap and bmap_or_alloc

- kernel-rs/src/proc.rs
- kernel-rs/src/spinlock.rs
* Closes https://github.com/kaist-cp/rv6/issues/324
* `SpinlockProtected::get_mut()`의 signature를 바꿨습니다. 이제 guard는 &mut 입니다. (교수님 말씀처럼 &self를 &mut self로 바꾸려면 `ProcessSystem`이나 `Kernel`을 &mut로 borrow해야되는 부분들이 생기는 것 같아, guard를 &mut로 바꿨습니다.)
https://github.com/kaist-cp/rv6/blob/7ecf1595d09c76786a290d11038dca129b6f7ce1/kernel-rs/src/spinlock.rs#L253-L257
* 더 이상 아래의 두 코드는 compile되지 않습니다.
```rust
static LOCK: RawSpinlock = RawSpinlock::new("test");
fn test() {
let v = SpinlockProtected::<i32>::new(&LOCK, 0);
let mut guard = v.lock();
let w_mut = {
let w = SpinlockProtected::<i32>::new(&LOCK, 1);
w.get_mut(&mut guard)
};
*w_mut = 2;
}
```
Error: w does not live long enough
```rust
static LOCK: RawSpinlock = RawSpinlock::new("test");
fn test() {
let v = SpinlockProtected::<i32>::new(&LOCK, 0);
let …
```
> [Closes #324] Fix SpinlockProtected::get_mut()'s signature

- kernel-rs/src/bio.rs
- kernel-rs/src/fs/inode.rs
Closes #325
Data in `Buf` may be assumed to be `u32`, so the `data` field in `Buf` must have an alignment of 4 bytes. To preserve the order between the fields in the source code, we use the C representation instead of the default one. By doing so, `Buf` in memory always begins with the `data` field. In addition, due to the `align(4)` modifier, `Buf` itself has an alignment of 4 bytes.
> [Closes #325]: make data of Buf have an alignment of 4 bytes

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sysfile.rs
Closes #328
* `InodeGuard`의 `tx: &FsTransaction` 필드를 없애고 `InodeGuard`의 메서드 중 `FsTransaction`이 필요한 메서드만 명시적으로 `FsTransaction`을 인자로 받도록 수정했습니다.
* `exec.rs`의 `exec`와 `sysfile.rs`의 `sys_chdir`은 `FsTransaction`을 사용하지는 않지만 할당되어 있던 inode를 해제할 수 있기 때문에 `begin_transaction`을 호출합니다. 이는 기존 C 코드에서 `begin_op`를 호출하는 것에 합치합니다. 반면, `file.rs`의 `read`는 더 이상 `begin_transaction`을 호출하지 않으며 이 역시 기존 C 코드에서 `begin_op`를 호출하지 않는 것에 합치합니다.
> [Closes #328] Remove FsTransaction from InodeGuard

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/kalloc.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/page.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/vm.rs
자세한 내용은 코드에 주석으로 있음.
* `Page`: 서로 다른 두 `Page`는 겹치지 않음.
* `RawPageTable`: V 플래그는 켜져 있고 R, W, X 플래그는 지워진 엔트리는 page-table 페이지를 가리킴. 임의 높이의 트리로 생각.
* `PageTable`: 3-level 트리 구조 유지. 임의의 `VAddr`을 받아 대응되는 `PAddr`을 내놓는 맵으로 생각.
현재는 `PageTable` 구조의 올바름을 보장할 수 있지만, `PageTable`이 가지고 있는 `PAddr`이 올바른 페이지에 대응된다는 사실을 보장할 수 없음. 따라서 `PageTable<UVAddr>::copy_out`과 같이 페이지 주소를 찾아 그 페이지에 데이터를 쓰거나 페이지로부터 데이터를 읽는 메서드의 안전성을 보장할 수 없음. 이는 `PageTable`의 invariant가 아니라 다른 타입의 invariant로 보장할 예정. 현재는 `Proc`이 `PageTable`을 가지고 있지만, 이 사이에 한 단계를 추가해 `Proc`은 `MemoryManager`를, `MemoryManager`는 `PageTable`를 가지고, `MemoryManager`의 invariant가 `PageTable`이 가지고 있는 주소의 올바름을 보장하도록 이후의 PR에서 수정할 예정.
> Refactoring VM by exploiting invariants of Page and PageTable

- kernel-rs/src/riscv.rs
- kernel-rs/src/vm.rs
Closes #341 
`usize`를 `i32` 대신 `PTE_*` 타입으로 사용합니다.
> [Closes #341] usize instead of i32 for PTE_*

- kernel-rs/src/exec.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/riscv.rs
- kernel-rs/src/vm.rs
* Closes https://github.com/kaist-cp/rv6/issues/295
1번
* **이제 `freeproc()`을 직접 call해야되는 경우는 `ProcessSystem::wait()`에서 `ZOMBIE` 상태의 child process을 reap하고 싶을 때 뿐입니다.** 그 외에는 `Process`의 `state`가 `STARTING1`인 경우, `ProcGuard::drop()`할때 알아서 call됩니다.
* `freeproc()`은 이제 `ProcGuard`의 method 중 하나입니다.
* 추가로, `STARTING1`과 `STARTING2`라는 새로운 state를 추가했습니다. 굳이 2개나 추가한 이유는 `ProcessSystem::fork()`때문입니다. (아래 코드의 주석 참고. 아주 잠깐동안 `ProcGuard`이 drop되는 부분이 있습니다.).
* `ProcessSystem::fork()`을 시작하자마자 `wait_lock`을 acquire하도록 변경한다면 굳이 2개일 필요가 없어지지만, 이러면 critical section의 길이가 길어지고 xv6이랑 약간 달라지는 것 같아 일단은 놔뒀습니다.
2번
* **proc_freepagetable을 `PageTable<UVAddr>::drop()`로 대체**했고, 지저분한 부분들을 조금 정리했습니다.(proc_freepagetable은 더 이상 사용되진 않지만 일단 놔뒀습니다.)
* 이를 위해, `PageTable`에 `num_usr_pages`라는 field를 추가했습니다. (`ProcData::sz`는 그대로 …
> [Closes #295] Replace freeproc(), proc_freepagetable() with ProcGuard::drop(), PageTable<UVAddr>::drop()

- kernel-rs/src/kalloc.rs
- kernel-rs/src/page.rs
- kernel-rs/src/vm.rs
Closes #339
"V 플래그는 켜져 있지만 RWX 플래그는 꺼져 있는 엔트리는 페이지 테이블을 가리킨다"는 성질을 `PageTableEntry`의 invariant로 변경했습니다. `PageTableEntry`의 invariant가 엔트리 수정 시에도 유지될 수 있도록 `set_inner`와 같이 invariant를 깰 수 있는 메서드를 없애고 다음과 같은 메서드를 추가했습니다.
* `set_table`: 페이지 테이블을 가리키는 엔트리로 만듦
* `set_entry`: 데이터 페이지를 가리키는 엔트리로 만듦
* `make_user_inaccessible`: `PTE_U`를 지워 유저 프로세스의 접근을 막음
* `invalidate`: 유효하지 않은 엔트리로 만듦
더 나은 메서드 이름을 제안해 주시면 좋을 거 같습니다.
> [Closes #339] Exploit invariant of PageTableEntry

- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- closes #332
---
주요 변경점입니다.
- `sys_*` 함수 중에서 https://github.com/kaist-cp/rv6/issues/332#issuecomment-759912575 에서 말씀하신 의도를 만족할 수 있는 부분만 분리했습니다. (내부 코드가 짧은 함수들은 그대로 유지)
- `sys_*` 함수들이 call하는 함수들은 `Result` type을 return 하도록 변경했습니다.
- `sys_exec`의 경우에는 `Kernel::exec`가 이미 기능을 하고 있다고 생각해서 변경하지 않았습니다.
- `fetchaddr` 도 `Result`를 return 합니다.
- `fdalloc`이 `Result<i32, Self>` 대신 `Result<i32, ()>`를 return 합니다.
---
https://github.com/kaist-cp/rv6/blob/f5f6a8f4ddc3e45a17feeaf529ec7f8f835e993e/kernel-rs/src/syscall.rs#L115
- 여기서 `ok_or!`등을 사용해서 `usize`로 변환하는 방향입니다.
> [closes #332] split sys_* functions into fetch part and helper function

- Makefile
- kernel-rs/src/param.rs
- kernel/param.h
Closes #345 
To build and test xv6 with higher optimization levels, this PR additionally provides `OPTFLAGS` option. e.g. `make qemu OPTFLAGS=-O3`.
> Enlarge filesystem to make usertests runnable with higher optimization level.

- kernel-rs/src/proc.rs
- kernel-rs/src/sleepablelock.rs
- kernel-rs/src/spinlock.rs
- kernel-rs/src/virtio_disk.rs
#241 작업을 하기 전에 먼저 `WaitChannel`의 지저분한 부분을 조금 다듬어봤습니다.
* 기존에는 `WaitChannel`에 대해서 sleep을 하기 위해서는 `SpinlockGuard`는 `sleep()`로, `SleepablelockGuard`는 `sleep_sleepable()`로, 그리고 `SpinlockProtected`는 `sleep_raw()`로 **여러가지로 API가 나눠져있는 걸 하나로 합쳤습니다.**
* 이를 위해, `Guard`라는 trait을 추가했습니다. (현재 `SpinlockGuard`, `SpinlockProtectedGuard`, `SleepablelockGuard`이 이걸 impl합니다.)
* 다만, 별개로, **현재 `SleepablelockGuard::sleep()`이 `unsafe`이 아닌데, 이래도 괜찮은지 잘 모르겠습니다.** 	
* 먼저, `WaitChannel::sleep()`이 `unsafe`한 이유는 `guard.sched()`을 call할때는 항상 `p->lock`이외에는 어떠한 RawSpinlock도 acquire한 상태여선 안되기 때문입니다. (`guard.sched()`내에서도 `assert_eq!((*kernel().mycpu()).noff, 1, "sched locks");`로 이걸 확인합니다). 그러나 `SleepablelockGuard::sleep()`은 내부에서 `WaitChannel::sleep()`을 사용하는데도 unsafe이 아닙니다.
> Fix WaitChannel's API

- .gitignore
- README-rv6.md
- bench.py
Performance evaluation 을 하기 위해서 usertests benchmark 를 하였습니다. 이를 위해:
- Filesystem 크기를 2배로 키웠습니다. ( Closes #345 )
- `usertests` 를 10번 실행하는 benchmark script 를 작성했습니다.
Benchmark 다음 세 가지를 비교하였습니다:
- xv6 with gcc -O3    (gcc: 10.2.0)
- xv6 with clang -O3   (clang: 11.0.0)
- rv6 with release mode
xv6-riscv 에도 동일한 수정을 하였습니다: https://github.com/efenniht/xv6-riscv/tree/bench 또한, xv6-riscv 는 GCC 확장을 사용하고 있어 해당 코드를 clang 에도 컴파일되도록 표준 문법으로 바꾸었습니다.
벤치마크 결과는 다음과 같습니다:
```
xv6 w/ gcc: 79.83 ± 1.04s
xv6 w/ clang: 118.87 ± 2.34s
rv6: 74.18 ± 0.78s
```
왠지 모르겠지만 rv6 가 더 빠릅니다 (??)
> Add benchmark script

- count_unsafe.py
`count_unsafe.py`를 실행할 때 `fs/*.rs` 파일들이 제대로 카운트되지 않는 버그가 있어 수정했습니다.
현재 unsafe line 수는 다음과 같습니다:
```
kernel-rs/src/virtio.rs: 6/76 = 7%
kernel-rs/src/riscv.rs: 154/274 = 56%
kernel-rs/src/sleepablelock.rs: 14/74 = 18%
kernel-rs/src/pipe.rs: 115/170 = 67%
kernel-rs/src/uart.rs: 11/155 = 7%
kernel-rs/src/console.rs: 97/158 = 61%
kernel-rs/src/vm.rs: 197/578 = 34%
kernel-rs/src/page.rs: 10/65 = 15%
kernel-rs/src/start.rs: 34/57 = 59%
kernel-rs/src/stat.rs: 0/10 = 0%
kernel-rs/src/sleeplock.rs: 13/92 = 14%
kernel-rs/src/utils.rs: 0/7 = 0%
kernel-rs/src/plic.rs: 18/22 = 81%
kernel-rs/src/etrace.rs: 0/117 = 0%
kernel-rs/src/trap.rs: 122/143 = 85%
kernel-rs/src/file.rs: 86/175 = 49%
kernel-rs/src/kalloc.rs: 13/45 = 28%
kernel-rs/src/memlayout.rs: 0/34 = 0%
kernel-rs/src/fcntl.rs: 0/9 = 0% …
```
> Fix bug: count unsafe of source codes in subdirectories.

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/kalloc.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/page.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/vm.rs
유저 프로세스 메모리를 관리하는 `UserMemory` 타입을 추가했습니다. `UserMemory`는 다음과 같은 invariant를 가집니다.
(For brevity, `pt` := `page_table`, and we treat `pt` as a function from `va` to `pa`.)
* `TRAMPOLINE` ∈ dom(`pt`) ∧ `pt(TRAMPOLINE)` = `trampoline`.
* `TRAPFRAME` ∈ dom(`pt`) ∧ `pt(TRAPFRAM)E` = `trap_frame`.
* If `va` ∈ dom(`pt`), `va` mod `PGSIZE` = 0 ∧ `pt(va)` mod `PGSIZE` = 0.
* If `va` ∈ dom(`pt`) where `va` ∉ { `TRAMPOLINE`, `TRAPFRAME` }, then `Page::from_usize(pt(va))` succeeds without breaking the invariant of `Page`.
* If `va` ∈ dom(`pt`) where `va` ∉ { 0, `TRAMPOLINE`, `TRAPFRAME` }, then `va - PGSIZE` ∈ dom(`pt`).
* `pgroundup(size)` ∉ dom(`pt`).
* If `size` > 0, then `pgroundup(size) - PGSIZE` ∈ dom(`pt`).
* `Page::from_usize(trap_frame)` succeeds without breaking the invariant of `Page`.
이제 …
> Add `UserMemory` type to exploit invariant of user process memory

- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/virtio.rs
- kernel-rs/src/virtio_disk.rs
* `Disk`가 `RawPage`를 받아 해당 페이지의 내부를 가리키는 포인터를 만드는 기존의 코드를 없애고, 처음부터 올바르게 align된 배열을 `Disk`가 가지고 있게 만들었습니다. 이를 통해 `Disk`가 자기 자신을 참조할 필요가 없게 되었습니다. 다만, 여전히 `Disk`의 배열의 주소를 MMIO 레지스터에 기록하기 때문에 이후에 가능하다면 `Disk`를 `Pin`으로 보호하는 것이 좋을 것 같습니다.
* `Descriptor`가 `Disk`에 있는 `desc` 배열의 특정 부분을 가리키는 포인터를 가지고 있던 것을 없애고, xv6 구현처럼 index를 나타내는 `usize`만 가지고 있도록 다시 바꾸었습니다. 
* 포인터를 가지고 있는 경우 해당 포인터가 유효한지 보장할 수 없기 때문에 기존 구현에 있던 아래와 같은 `Deref` 및 `DerefMut` 구현은 올바르지 않습니다.
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/virtio_disk.rs#L123-L135
따라서 `Descriptor`가 가지고 있는 포인터를 사용하려면 반드시 `unsafe`가 필요하고 이는 `unsafe`를 불필요하게 늘립니다.
* 반면 index만 가지고 있고 이 index를 사용해 `desc` 배열에 접근하는 것은 언제나 안전합니다. Rust에서는 배열에 접근할 때 index를 검사하므로 xv6에 비해 약간의 성능 손해가 발생할 수 있습니다. 그러나, 현실적으로 rv6 전체에서 배열 접근을 …
> Refactoring virtio_disk

- kernel-rs/src/file.rs
- kernel-rs/src/pipe.rs
Closes #365 
* #356 에서의 변경사항 중 `Pin` API와 관련없는 내용만 따로 빼서 새롭게 PR을 만들었습니다. (주로 `Pipe`에 대한 변경사항입니다.)
* `Pipe`의 `Drop` trait을 추가했고 `Copy`, `Clone` trait을 없앴습니다.
* 추가로, `Pipe::copy`가 `unsafe`일 필요가 없는 것 같아서 없앴습니다. (혹시 `unsafe`이여야하는 이유가 있다면 말씀해주세요.)
* kernel.rs에 있던 주석을 일부 지웠습니다. (https://github.com/kaist-cp/rv6/pull/356#discussion_r564504081)
> [Closes #365] Fix TODOs in pipe.rs

- Makefile
- kernel-rs/src/lib.rs
Closes #382 
* lib.rs에서 `cargo doc`와 관련된 lint를 금지하는 부분을 주석처리했습니다.
* Makefile에 `make doc` 기능을 추가했습니다.
* README-rv6.md에도 관련 내용을 추가하는게 좋을까요?
참고로, doc을 읽고 싶을때는 kernel-rs/target/riscv64gc-unknown-none-elfhf/doc/rv6_kernel/index.html 을 여시면 됩니다.
> [Closes #382] Add `make doc`.

- kernel-rs/src/arena.rs
- kernel-rs/src/bio.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/fs/superblock.rs
- kernel-rs/src/virtio_disk.rs
Closes #383
* `read_head`에서 `buf_unforget` 대신 `disk.read` 사용. `Arena::unforget` 삭제.
* `Buf`가 `ManuallyDrop<BufUnlocked>`를 가지게 있게 하여 `transmute` 없이 `unlock` 구현.
* 필요없는 `unsafe` 제거. `unsafe` 블록에 주석 추가.
* 가능한 경우 포인터 대신 slice 사용.
> [Closes #383] Refactoring bio.rs and log.rs

- kernel-rs/src/arena.rs
- kernel-rs/src/bio.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
* ~`Arena`의 unsafe reasoning을 위한 PR입니다.~
* ~일단 `ArrayPtr`과 `MruPtr`이 가지고 있는 포인터를 `*mut`에서 `NonNull`로 바꾸었습니다.~
* ~코드를 보다 보니 `Arena` 구현에 관련된 질문이 몇 가지 생겼는데 해당 위치에 comment로 달아 두겠습니다.~
*edited*
`ArrayArena`의 unsafe reasoning을 위한 PR입니다.
* `ArrayPtr`과 `MruPtr`이 가지고 있는 포인터를 `*mut`에서 `NonNull`로 바꾸었습니다.
* 사용되지 않는 정의인 `impl<A: Arena, T: Clone + Deref<Target = A>> Arena for T`를 없애고 `Arena` 트레잇에 `Rc`를 반환하는 메서드를 추가했습니다.
* `ArrayPtr`이 해당 핸들을 만든 `ArrayArena`가 살아 있는 동안만 살아 있도록 `ArrayPtr`에 lifetime parameter를 추가했습니다. 이에 따라 `Rc`에도 lifetime parameter가 추가되었습니다.
`MruArena`는 이 PR에서 다루지 않습니다.
> Unsafe reasoning in ArrayArena

- kernel-rs/src/arena.rs
- kernel-rs/src/file.rs
- kernel-rs/src/pipe.rs
Closes #374 
* `ArrayPtr`와 `AllocatedPipe`이 `Send`를 impl하도록 바꿨습니다. 이러면 `File`는 `Send`이 자동으로 `impl`됩니다. (docs로 확인했습니다.)
* `Send`이여도 괜찮다고 생각하는 이유를 간단히 적어놨습니다.
> [Closes #374] Make `File` auto impl `Send` trait.

- kernel-rs/Cargo.lock
- kernel-rs/Cargo.toml
- kernel-rs/src/arena.rs
- kernel-rs/src/bio.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/list.rs
- kernel-rs/src/pinned_kernel.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sleepablelock.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/spinlock.rs
- kernel-rs/src/virtio_disk.rs
Partially resolves # 378.
* `T: Unpin`인 경우에만 (즉, `T`가 move되어도 상관없는 경우에만) `Spinlock`, `SpinlockGuard`와 같은 lock 및 guard들이 `get_mut()`, `get_mut_unchecked()`, `DerefMut`을 impl하도록 바꿨습니다. 그 대신, `get_pin()`을 추가했습니다.
* 추가적으로 ,다른 PR에서 lock과 guard들을 더 정리할 계획입니다.
* `ListEntry` API가 `Pin`을 사용하게끔 바꿨습니다.
* `MruArena`, `MruEntry`에서 mutable reference가 필요할 때는 항상 `Pin<&mut ...>`을 사용하게끔 바꿨습니다.
* 편의를 위해 pin_project crate를 사용했습니다. move되선 안되는 field에는 #[pin]을 붙여서 `Pin`으로만 접근하도록 제한했습니다. 다만 pin_project가 procedural macro를 사용해서인지 dependency를 약 10개나 늘려버립니다. 참고로, procedural macro를 쓰지 않는 pin_project_lite도 있기는 한데 이건 기능이 제한적입니다.
EDIT:
* 특히, `Pin`의 안전성을 깔끔하게 보장하기 위해서 `PinnedKernel`이라는 struct 및 static 변수를 추가했습니다. 지금은 `BcacheInner`만 들어있지만 추후 `Pin`이 필요한 struct들을 `Kernel`에서 여기로 옮길 계획입니다.
* …
> [Sub-issue of #378] Add `PinnedKernel`, and use `Pin` in locks, `MruArena`, and `MruEntry`

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sleepablelock.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/virtio_disk.rs
- kernel-rs/src/vm.rs
- closes #354 , closes #258
주요 변경사항입니다.
- `myproc()` 을 `Kernel`의 메소드로 이동
- `struct ExecutingProc` 추가: `*mut Proc`을 감싸는 struct
- `kernel().myexproc()` 추가: `myproc()`에서 `Proc`이 존재함을 확인하고 `ExecutingProc`을 리턴
- `usertrap()`에서 sys_* 함수들에 `ExecutingProc`을 전달
- proc이 null이 아니어야 하는 경우에는 `myproc()`의 사용을 모두 `myexproc()`으로 수정했습니다.
> [closes #354, #258] myproc()의 사용을 줄이고, usertrap()에서 syscall 함수로 proc전달

- kernel-rs/src/console.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- closes #346 , closes #363 
주요 변경점입니다.
- prod id type인 `Pid`를 만들었습니다.
- `ProcInfo`에 있던 `pid`를 `AtomicI32`로 바꾸고 `Proc`으로 옮겼습니다.
- `Proc`에서 unsafe하게 정의되어 있던 `state()`함수를 `ProcGuard`로 옮겼습니다.
- `ProcGuard`없이 `state`에 접근하지 않습니다.
> [Closes #346, #363] Atomicpid, proc id type, state in procguard

- kernel-rs/src/proc.rs
- kernel-rs/src/riscv.rs
- kernel-rs/src/spinlock.rs
- kernel-rs/src/start.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/virtio.rs
- kernel-rs/src/virtio_disk.rs
Inline assembly를 사용해 레지스터의 값을 읽기만 하는 함수는 메모리 안전성을 깨거나 data race를 일으키지 않으므로 unsafe를 제거했습니다.
> Remove unsafe of functions reading registers

- kernel-rs/src/bio.rs
- kernel-rs/src/console.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sleepablelock.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/spinlock.rs
- kernel-rs/src/trap.rs
기존 `Spinlock`, `Sleeplock`, `Sleepablelock`의 `get_mut_unchecked`는 `&self`로부터 `&mut`을 만들어 내는 위험한 메서드였습니다.
https://github.com/kaist-cp/rv6/blob/1c9ed841809b4758a6c7bd999015ccd820ba2eaa/kernel-rs/src/spinlock.rs#L201-L210
Rust에서 굉장히 강력한 가정을 제공하는 `&mut` 대신, 아래와 같이  `*mut`을 반환함으로써 UB의 가능성을 줄일 수 있습니다. 이 경우 메서드를 호출한 쪽에서 raw pointer를 사용할 때 unsafe 블록을 열고 안전성을 확인해야 하므로, 더 이상 이 메서드가 unsafe일 필요가 없습니다.
https://github.com/kaist-cp/rv6/blob/ca67ebe897d57f593ac71a2c5c3070fc7a3ec184/kernel-rs/src/spinlock.rs#L201-L206
만약 `&mut`이 필요하고 `&mut`의 유일함을 guard를 사용해 보장할 수 있다면, 아래처럼 해당 guard의 메서드가 raw pointer를 reference로 변환하도록 하면 됩니다.
https://github.com/kaist-cp/rv6/blob/ca67ebe897d57f593ac71a2c5c3070fc7a3ec184/kernel-rs/src/fs/inode.rs#L229-L239
> Fix get_mut_unchecked of locks

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- closes #398 
sync-up에서 논의했던 대로 `CurrentProc`을 사용하면, 관련 함수에 `CurrentProc`을 전달할때 move되는 문제가 있기 때문에 `deref_mut_data`를 사용하는 곳에 `&mut CurrentProc`을 전달했습니다.
- 기존에 `Proc`에 있던 `deref_mut_data`를 `CurrentProc`의 함수로 이동
- `ProcGuard`에 `deref_mut_data`함수 추가
> [Closes #398] use &mut CurrentProc, deref_data from CurrentProc

- kernel-rs/src/arena.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/list.rs
- kernel-rs/src/proc.rs
개별적인 PR로 만들기는 애매한 자잘한 TODO들을 모아봤습니다.
* `MruEntry`가 `&ListEntry`로부터 `&mut MruEntry`를 얻던 부분을 변경했습니다. 이제 `Pin<&mut ListEntry>`로부터 `Pin<&mut MruEntry>`를 얻습니다. https://github.com/kaist-cp/rv6/commit/a3dbea939571d272765655247dda22a30ce84d44
* `Kernel`의 initialization이 끝난 후에도 `Pin<&mut Kernel>`로 `Kernel`을 접근하는 곳이 있어서 `&Kernel`로 접근하도록 변경했습니다. https://github.com/kaist-cp/rv6/commit/2ed78dbbcfb01dc75bdf957d01546c9928128122
* Closes #416 : `ProcInfo::child_wait_channel`을 `Proc`으로 옮겨봤습니다. https://github.com/kaist-cp/rv6/commit/82417413e66aa667f247951d9e761e26ee093663
* 혹시, 이 부분에 대해서 다른 생각이 있으시다면 말씀해주시면 감사드리겠습니다. @Medowhill
> Fix minor issues

- kernel-rs/src/arena.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/pinned_array.rs
- kernel-rs/src/proc.rs
Closes #410 
* `PinnedArray`라는 struct를 추가했습니다.
* `pin_project`의 경우, struct A가 struct B를 own하고 있다면 `Pin<&mut A>` -> `Pin<&mut B>`로 **safe**하게 넘어가는 방법을 제공합니다.
* 그러나, `Pin<&mut [A; N]>` -> `Pin<&mut A>`로 넘어가는 방법은 제공하지 않는 것으로 보입니다. 그러므로, 불필요하게 unsafe fn인 `Pin::get_unchecked_mut()`나 `Pin::new_unchecked()`를 사용해서 넘어가야 합니다.
* `PinnedArray`는 위와 같은 불필요한 unsafe 과정을 type안에 가두고 **safe한 API만 제공**합니다. 또, `Index`, `IntoIterator` trait을 impl하며, 특히 `Pin<&mut PinnedArray<T, N>>`을 iterate하려고 하면 자동으로 `Pin<&mut A>`가 나옵니다.
> [Closes #410] Add `PinnedArray`

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/riscv.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/vm.rs
* 파일 시스템에 관련된 syscall을 처리하는 코드의 불필요한 unsafe를 제거하고 남은 unsafe에는 안전성을 설명하는 주석을 달았습니다.
* `InodeFileType`과 `InodeFileTypeGuard`를 추가했습니다. `InodeFileType`은 `FileType`이 `Inode`인 경우에 사용되며, `ip`가 lock되어 있을 때만 `off`에 접근할 수 있도록 합니다.
> Unsafe reasoning of file-related syscalls

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/vm.rs
`Proc`의 invariant로 다음을 추가했습니다.
```rust
/// * If `info.state` != `Procstate::UNUSED`, then
///   - `data.trap_frame` is a valid pointer, and `Page::from_usize(data.trap_frame)` is safe.
///   - `data.memory` has been initialized.
///   - `data.cwd` has been initialized.
```
이 invariant에 의해 `CurrentProc`에서는 `trap_frame`, `memory`, `cwd`에 안전하게 접근할 수 있습니다. 해당 필드에 안전하게 접근하는 메서드를 `CurrentProc`에 추가했습니다. `CurrentProc`이 아닌데 사용하는 경우에는 unsafe가 필요하며 왜 해당 unsafe가 안전한지 주석으로 추가했습니다.
> exploiting invariants of ProcData

- count_unsafe.py
이미 count-unsafe를 설치하신 분들은 `cargo uninstall count-unsafe`를 통해 기존의 count-unsafe를 삭제해 주셔야 합니다.
> Closes #419

- kernel-rs/src/fs/mod.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/virtio.rs
- kernel-rs/src/virtio/mod.rs
- kernel-rs/src/virtio/virtio_disk.rs
- kernel-rs/src/virtio_disk.rs
`MmioRegs`를 `write`하게되면 side effect으로 인해 UB가 발생할 수 있으므로, unsafe이여야할 것 같습니다.
https://github.com/kaist-cp/rv6/pull/427#issuecomment-783301930
https://github.com/kaist-cp/rv6/pull/427#issuecomment-783808771
https://github.com/kaist-cp/rv6/pull/427#issuecomment-785499746
* hafnium에서 했던 것과 비슷하게 바꿔봤습니다. (ex: https://github.com/kaist-cp/hafnium-verification/blob/hfo2/hfo2/src/cpu.rs)
* `MmioRegs`를 write하는 것은 항상 unsafe입니다.
* 다만, safe하게 write해도 되는 register는 따로 safe한 function으로 unsafe 부분을 감쌌습니다.
* `MmioRegs`를 read하는 건 일단은 safe로 놔두었습니다.
* EDIT: 추가로, virtio.rs와 virtio_disk.rs를 virtio module로 합쳐봤습니다.
> Change `MmioRegs::write` into unsafe fn.

- kernel-rs/src/console.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sleepablelock.rs
- kernel-rs/src/sleeplock.rs
- kernel-rs/src/spinlock.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/uart.rs
- kernel-rs/src/virtio/virtio_disk.rs
- kernel-rs/src/vm.rs
Closes #420
* `Proc`의 `parent`는 `MaybeUninit`. `parent`의 초기화는 `ProcessSystem::init`에서 진행. 따라서 `parent`에 접근하는 모든 메서드는 `init`이 이미 호출된 상태여야만 안전하게 사용될 수 있고, 메서드 호출 시에 추가적인 가정이 필요한 것이므로 unsafe 메서드가 될 수밖에 없음.
* 이 문제를 해결하기 위해서는 `parent`가 초기화되었다는 것을 나타내는 타입이 필요. 해당 타입의 값은 `init`이 호출된 상태에서만 만들 수 있으므로 unsafe 메서드를 통해 만들어짐. 해당 타입의 값은 `parent`에 접근하는 메서드를 제공하며, 이 메서드는 unsafe가 아님.
* `InitializedKernel` 추가: 초기화가 끝난 `Kernel`을 타입으로 나타냄. `Kernel`에서 초기화 없이 접근하면 위험한 값들을 안전하게 접근하는 메서드를 제공. `initialized_kernel`을 호출해 얻을 수 있으며, `initialized_kernel`은 unsafe 함수이기 때문에, 커널의 초기화가 끝났다는 것을 보장할 수 있는 곳(`usertrap` 등)에서만 호출해야 함. 현재는 `InitilalizedProcessSystem`을 만들기 위해서만 사용하지만, 초기화가 필요한 다른 필드(예를 들면 `bcache`)에 안전하게 접근하는 데도 사용할 수 있음.
* `InitilalizedProcessSystem` 추가: 초기화가 끝난 `ProcessSystem`. `initial_proc`과 `process_pool`에 있는 …
> Closes #420

- kernel-rs/src/arena.rs
- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lock/sleepablelock.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/lock/spinlock.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/uart.rs
- kernel-rs/src/virtio/virtio_disk.rs
- kernel-rs/src/vm.rs
#267 을 부분적으로 해결하는 PR입니다. 다음 파일에 있는 `kernel_builder` 호출을 없앴습니다.
* fs/path.rs
* `Path::root`를 `Itable::root`로 옮김. 이에 따라 `ProcsBuilder::user_proc_init`이 init 프로세스의 초기 cwd를 인자로 받음.
* `Path::namei`와 `Path::nameiparent`가 `&Itable`을 인자로 받음.
* fs/log.rs
* `Log`의 대부분 메서드가 `&Disk`를 인자로 받음.
* fs/inode.rs (partial)
* `InodeGuard::dirlink`와 `InodeGuard::dirlookup`이 `&Itable`을 인자로 받음.
* file.rs (partial)
* `FileType::Device`가 `major`로 `u16` 대신 `&Devsw`를 가짐.
* `File::write`이 `&FileSystem`을 인자로 받음.
* sysfile.rs
* `create`을 전역 함수에서 `Kernel`의 메서드로 바꿈.
* pipe.rs
* `AllocatedPipe::alloc`을 `Kernel::allocate_pipe`로 옮김.
* `AllocatedPipe::close`가 `Page`를 직접 free하는 대신 그냥 반환.
`'b: 'a`일 때 `Rc<'b, T, S>`를 `Rc<'a, T, S>`의 서브타입으로 취급하기 위해 `arena.rs`에 `narrow_lifetime`을 정의했습니다. 알아서 서브타입으로 간주가 되면 좋겠는데, 이유는 잘 모르겠지만 그렇게는 …
> Partially resolves #267

- kernel-rs/src/arena.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
Closes #393
기존의 rv6는 synchronization 관련하여 **잠재적인 버그** 1개와 **early break 관련된 버그** 1개가 있었던 것으로 보입니다.
* 잠재적인 버그
* thread가 어떤 `ArenaObject`를 finalize하고 있을때 `Arena::reacquire_after`를 사용하면, 잠깐동안 `Arena`의 lock이 해제되므로, 이 사이에 다른 thread가 실수로 이미 finalize되고 있는 `ArenaObject`을 `find_or_alloc`하려고 시도할 수 있습니다.
* early break 관련된 버그
* 7b493ce 에서 추가한 break로 인해, xv6와 rv6의 semantics가 달라지게 되었습니다.
* 기존에는 모든 entry를 한번씩 검사해본 후에만 alloc을 시도하였는데, break을 추가한 이후에는 빈자릴 찾자마자 그 곳에 alloc을 시도하게 되었습니다.
* 잠재적인 버그
* 이런 행위를 시도하면 안된다는 점을 나타내기 위해서, `Arena::reacquire_after`를 unsafe fn으로 변경했습니다.
* 참고로, xv6는 이런 행위를 시도하지 않는 것을 보입니다. (이유는 주석으로 적어놨습니다.)
* early break 관련된 버그
* break을 없앴습니다. 즉, 다시 xv6의 semantics로 되돌렸습니다.
> [Closes #393] Fix Arena's synchronization

- kernel-rs/src/console.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/proc.rs
* `ProcGuard`가 `&ProcBuilder` 대신 `&Proc`을 가지고 있게 했습니다.
* `init`을 제외한 나머지 메서드(`user_proc_init`, `alloc` 등)를 `ProcsBuilder`에서 `Procs`로 옮겼습니다.
`Procs`의 typestate는 세 종류입니다.
1. `parent`와 `initial_proc`이 초기화되지 않음.
2. `parent`는 초기화되었지만 `initial_proc`이 초기화되지 않음.
3. `parent`와 `initial_proc`이 초기화됨.
기존 코드에서는 1, 2가 `ProcsBuilder`에 의해 표현되고 3만 `Procs`에 의해 표현되었습니다. 이로 인해, `alloc`이 `ProcsBuilder`의 메서드가 되어야만 하고 `ProcGuard`가 `&ProcBuilder`를 가져야만 하는 문제가 있었습니다.
그래서 이 PR에서는 1만 `ProcsBuilder`로 표현하고 2, 3을 `Procs`로 표현하도록 고쳤습니다. 이로 인해 생긴 문제는 `Procs`가 `initial_proc`의 초기화를 보장하지 못하기 때문에 `initial_proc`에 접근할 때 null 검사를 해야 한다는 점입니다. 그러나 이로 인한 성능 손해가 무시할 정도로 작으며, 그 비용을 감수하고 위 목표를 달성하도록 코드를 리팩토링하는 것이 더 바람직하다고 판단했습니다.
세 종류의 typestate를 각각 별도의 타입으로 표현하는 방법도 가능하겠지만, 2가 `init`과 `user_proc_init` 사이의 아주 잠깐 동안만 존재하는 상태이기 때문에, 2를 …
> Make ProcGuard have &Proc, not &ProcBuilder

- kernel-rs/src/exec.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/path.rs
- kernel-rs/src/sysfile.rs
`namei`와 `nameiparent`를 `Path`에서 `Itable`로 옮겼습니다.
> [Closes #442] namei & nameiparent: Path -> Itable

- kernel-rs/src/arena.rs
- kernel-rs/src/bio.rs
- kernel-rs/src/list.rs
Closes #450
기존의  intrusive linked list에는 unsound한 부분들이 있습니다.
* 예를 들어, `ListEntry::prev`나 `ListEntry::next`는 `Pin<&mut Self>`를 리턴하는데, 사실 node가 언제 mutate/drop될지 알 수 없으므로 이런 type을 리턴하는게 unsound 합니다.
* `ListEntry`의 API를 잘못 사용하면, linked list 구조를 망가뜨릴 수 있습니다. 이를 막기 위하여, `List`와 같은 type을 추가하는 것이 좋을 것 같습니다.
* `List`와 `ListEntry`의 API들이 `&Self`나 `Pin<&mut Self>`와 같은 type이 아닌, `*const Self`을 리턴하도록 변경했습니다.
* 항상 linked list 구조를 가지는 `List`라는 type을 추가했습니다.
* intrusive linked list node임을 나타내는 `ListNode` trait을 추가했습니다.
> [Closes #450] Fix unsoundness in list.rs.

- kernel-rs/src/fs/inode.rs
- kernel-rs/src/stat.rs
`Stat`이 사용되는 곳이 fstat의 결과를 만드는 부분밖에 없기 때문에 최소한으로만 수정해 보았습니다.
> Closes #462

- kernel-rs/src/arena.rs
- kernel-rs/src/bio.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/fs/superblock.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/virtio/virtio_disk.rs
Closes #444 
* `Rc`, `RcInode`, `RcFile`의 lifetime parameter를 모두 없앴습니다.
* `Rc<'s, A, &A>` -> `Rc<T, A>`. 여기서 `T`는 `A`의 `Data` type입니다.
* `RcInode<'s>` -> `RcInode`
* `RcFile<'s>` -> `RcFile`
* sysfile.rs에 정의되어 있던 `Kernel`의 method들 중에서, `&'static self`를 받을 필요가 없는 method들을 `&self`로 변경했습니다.
> [Closes #444] Remove lifetime from `Rc`, `RcInode`, `RcFile`

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/kalloc.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/vm.rs
* `Allocator` 타입을 추가
* zero-sized struct
* unsafe 메서드인 `new_unchecked`를 통해 새 `Allocator`를 만들 수 있음
* `alloc` 메서드는 `kernel_builer().alloc()`을 호출
* `free` 메서드는 `kernel_builer().free()`를 호출
* `UserMemory`와 `PageTable`이 각각 `Allocator`를 가짐
* `UserMemory`의 `Allocator`는 유저 프로세스가 사용할 페이지를 제공
* `PageTable`의 `Allocator`는 페이지 테이블 자기 자신이 사용할 페이지를 제공
* 두 `Allocator`의 역할이 분명히 구분되므로 `UserMemory` 안에 있는 `PageTable`이 자신만의 `Allocator`를 가진다고 해도 크게 이상하지 않음. 어차피 `Allocator`는 zero-sized struct이므로 runtime overhead도 없음.
* Alternative designs:
* `UserMemory`는 `Allocator`를 가지되 `PageTable`은 가지지 않음: `PageTable`의 많은 메서드가 `UserMemory`로부터 게속 `Allcoator`를 인자로 받아야 해서 코드가 장황해짐. `PageTable`의 auto drop도 불가능해짐.
* `PageTable`은 `Allocator`를 가지되 `UserMemory`는 가지지 않음: `PageTable`은 페이지 테이블 자료 구조만을 나타내는 타입이고 `UserMemory`는 유저 프로세스의 …
> Closes #344: add Allocator

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/sysfile.rs
- kernel-rs/src/sysproc.rs
- kernel-rs/src/vm.rs
* #458 에서 `UserMemory`의 일부 메서드(`copy_in`, `copy_out` 등)는 `&Spinlock<Kmem>`을 인자로 받을 필요가 없는데도 인자를  받도록 잘못 수정해 버렸습니다. 인자를 받지 않도록 다시 고쳐 이를 해결했습니다.
* `argstr` 등의 syscall 인자를 가져 오는 함수가 예전에는 전역 함수로 정의되어 있었는데, #458 에서 `kmem`에 접근할 필요가 있어 `Kernel`의 메서드로 옮겼습니다. 이제 `kmem`이 필요하지 않기 때문에 `Kernel`의 메서드일 필요는 없어졌는데, 전역 함수보다는 `CurrentProc`의 메서드로 간주하는 것이 더 합리적인 설계라 생각하여 그렇게 수정했습니다.
> Remove unnecessary allocator arguments

- kernel-rs/src/trap.rs
Closes #311 
기존처럼 `devintr()`안에서 `println!`을 쓰면 아주 가끔씩 stack overflow가 발생하는 것으로 보입니다.
xv6의 semantics를 그대로 따르려면 `println!`을 써야겠지만,
stack overflow가 자주 발생하는 것 같아 이를 `panic!`으로 변경한 후 관련 주석을 추가했습니다.
> [Closes #311] Use `panic!` instead of `println!` in `devintr`.

- kernel-rs/src/kalloc.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/page.rs
- kernel-rs/src/pipe.rs
원래 `Kmem`은 자체적인 intrusive linked list를 사용하도록 구현되어 있었는데, 이를 이미 rv6가 가지고 있는 instrusive linked list 타입인 `List`를 사용하도록 수정했습니다. 원래 `Kmem`에서는 singly linked list를 사용하지만 `List` 타입은 doubly linked list인 것 등의 사소한 차이가 있고, 이로 인해 약간의 runtime overhead가 추가될 수는 있겠으나 무시할 수 있을 정도라고 생각합니다. 어차피 핵심은 `Kmem`이 intrusive linked list로 구현되어야 한다는 점이니, `Kmem`을 이미 존재하는 `List` 타입을 사용해 구현하는 것이 더 바람직한 방향인 것 같습니다.
> Use `List` for `Kmem`

- kernel-rs/Cargo.lock
- kernel-rs/Cargo.toml
- kernel-rs/src/arena.rs
- kernel-rs/src/bio.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/lib.rs
Closes #371 
`ArrayArena`/`MruArena`의 `new` method를 변경했습니다.
기존:
```Rust
pub const fn new(entries: [RcCell<T>; CAPACITY]) -> Self; // ArrayArena
pub const fn new(entries: [MruEntry<T>; CAPACITY]) -> Self; // MruArena
```
변경 후:
```Rust
pub const fn new<D: Default>() -> Self; // ArrayArena
pub const fn new<D: Default>() -> Self; // MruArena
```
-----
* 기존에는 caller가 직접 초기화된 배열을 제공하는 형태였기 때문에, caller가 malicious한 배열을 제공하게 되면 문제가 생길 수 있었습니다.
* 변경 후에는 `ArrayArena`/`MruArena`가 직접 배열을 만들고 초기화합니다.
* 이를 위해서, `Default` trait을 요구하도록 변경했습니다. (`const fn`안에서는 closure나 function pointer를 사용할 수 없는 것으로 보입니다.)
* 특히, `Default` trait을 `const fn`안에서 사용하기 위해서, `#![feature(const_impl_trait)]`을 사용했습니다.
> [Closes #371] Use `const Default` trait in arena.

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/lock/sleepablelock.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall/file.rs
- kernel-rs/src/syscall/mod.rs
- kernel-rs/src/syscall/proc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/virtio/virtio_disk.rs
현재의 커널 스레드가 어떤 커널의 스레드이며 어떤 유저 프로세스를 위한 것인지 나타내는 `KernelCtx` 타입을 추가했습니다.
```rust
pub struct KernelCtx<'p> {
pub kernel: &'p Kernel,
pub proc: CurrentProc<'p>,
}
```
`CurrentProc`은 mutable하게 접근하면서 `Kernel`에는 immutable하게 접근해야 하는 경우가 꽤 있기 때문에, lifetime 문제가 생기지 않도록 두 필드를 각각 접근해야 합니다. 그래서 `CurrentProc` 안에 `&Kernel`을 넣는 대신 `&Kernel`과 `CurrentProc`을 모두 가지고 있는 타입인 `KernelCtx`를 새로 만들고, 기존에 `CurrentProc`을 전달하던 곳에서 `KernelCtx`를 전달하도록 수정했습니다.
> Add `KernelCtx`

- kernel-rs/src/util/branded.rs
- kernel-rs/src/util/mod.rs
Partially resolves #479 
* `Branded<'id, T>`를 추가했습니다.
* 이 type을 사용하면 rv6에서 branded type를 구현할 수 있습니다. 즉, 서로 다른 instance끼리의 관계를 표현할 수 있습니다.
* 이 PR을 먼저 merge한 후, rv6에서 `Branded`를 활용하는 PR들(ex: `Procs`, `Arena`, 등)을 만들 계획입니다.
> [Closes #479] Add `Branded<'id, T>`

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall/file.rs
- kernel-rs/src/syscall/mod.rs
- kernel-rs/src/syscall/proc.rs
- kernel-rs/src/trap.rs
참고: https://github.com/kaist-cp/rv6/pull/490#discussion_r614735246
* `KernelCtx`의 `kernel`와 `proc` field를 private field로 변환했습니다.
```Rust
pub struct KernelCtx<'p> {
kernel: &'p Kernel,
proc: CurrentProc<'p>,
}
impl<'p> KernelCtx<'p> {
pub fn kernel(&self) -> &'p Kernel {
&self.kernel
}
pub fn proc(&self) -> &CurrentProc<'p> {
&self.proc
}
pub fn proc_mut(&mut self) -> &mut CurrentProc<'p> {
&mut self.proc
}
}
```
* 이외에는, 그저 기계적으로
* `self.kernel` -> `self.kernel()`로
* `self.proc` -> `self.proc()` (또는 `self.proc_mut()`)
로 변환한 것 뿐입니다.
> Make `KernelCtx::{kernel, proc}` fields into private

- kernel-rs/src/console.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/lock/sleepablelock.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall/file.rs
- kernel-rs/src/syscall/mod.rs
- kernel-rs/src/syscall/proc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/virtio/virtio_disk.rs
Partially resolves #479 
Partially resolves #494 
#479 에서 설명한 것처럼, `Procs::{fork, wait, exit_current}`와 같은 method들은 여러개의 `Procs`가 존재할 수 있다면 memory safety bug가 생길 수 있습니다.
* ex1: 현재 `Procs::{fork, wait, exit_current}` method들에서는 먼저 `Procs::wait_lock`을 acquire한 후 `CurrentProc`의 parent field를 변경합니다
* 만약 엉뚱한 `Procs`의 `wait_lock`을 acquire하게되면, `CurrentProc`의 parent field를 lock을 잡지 않고도 read/write할 수 있게 됩니다.
* 그러므로, 지금은 `Proc`의 내부에 `Procs`의 `wait_lock`을 가리키는 reference를 별도로 저장해놓고 있습니다. (즉, 추가적인 runtime cost를 사용하고 있습니다.)
* 이 runtime cost를 safe하게 없애려면, `Procs`와 `CurrentProc`이 서로 연결되어 있음을 `Branded`를 통해 표현해야 합니다. 이러면, `Proc`의 내부에 추가적인 field를 저장할 필요가 없어집니다. (추가적으로, 이렇게 하면 `ProcsBuilder::init`의 unsafe를 어느정도 줄일 수 있을 것 같습니다.)
* ex2: `Procs::fork`는 새로운 `Proc`을 만든 후, `Proc::parent` field가 `CurrentProc`을 …
> [Closes #479] Use `Branded` to remove (potential) unsafe in `Procs`

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/syscall/file.rs
- kernel-rs/src/virtio/virtio_disk.rs
- kernel-rs/src/vm.rs
`kernel` (또는 그 variant들) 전역 함수 호출을 일부 없애는 PR입니다.
* `Disk`의 메서드들이 `&Bcache`나 `CurrentProc`을 필요로 하므로 `&KernelCtx`를 인자로 받도록 했습니다.
* `FsTransaction`, `Log`의 메서드들이 `Disk::read,write`을 호출하거나 `&Bcache`를 필요로 하므로 `&KernelCtx`를 인자로 받도록 했습니다.
* `inode.rs`의 메서드들이 `Disk`/`FsTransaction`의 메서드를 호출하거나 `&Itable`/`&FileSystem`을 필요로 하므로 `&KernelCtx`를 인자로 받도록 했습니다.
* 일부 메서드는 `KernelCtx`의 메서드가 되어야 할 수도 있는데, 일단 그런 고민은 하지 않고 `&KernelCtx`를 인자로 받도록 일괄적으로 수정했습니다.
* `InodeGuard`의 `read_internal`이 없어지고 `read_kernel`과 `read_user`에 코드 중복이 다소 생겼습니다. `read_kernel`은 유저 메모리에 접근하지 않으므로 `&KernelCtx`로 충분하지만, `read_user`는 유저 메모리에 접근하기 때문에 `&mut CurrentProc`이 필요하므로 `&mut KernelCtx`가 필요합니다. 이전처럼 공통 부분을 `read_internal`로 정의하려면 `read_internal`이 `&mut KernelCtx`를 받아야 하고, 그러면 `read_kernel`에서도 `&mut KernelCtx`를 요구하게 되며, …
> Remove global function calls (`kernel` variants)

- kernel-rs/src/arena.rs
- kernel-rs/src/lib.rs
Partially resolves #479 
Partially resolves #494 
`Arena::{dup, dealloc}`와 같은 method들은 주어진 `handle`이 `self`로부터 allocated된 것인 경우에만 사용해야 합니다. (`Rc::from_unchecked`도 마찬가지입니다.)
EDIT: 추가적으로, 이제보니 기존의 `Arena::{find_or_alloc_handle, alloc_handle}`method들에는 문제가 있었던 것으로 보입니다. 만약, user가 `Arena` trait을 구현할 때, 위 method들이 엉뚱한 `Arena`로부터 획득한 `Ref`를 리턴하도록 하면 synchronization 문제가 생깁니다.
* 이 문제는 `Branded`를 이용해서 `ArenaRef`와 `Handle`이 동일한 `'id`를 가지도록 강제하면 해결될 것 같습니다.
기존에는 이를 나타내기 위해 위 method들을 unsafe fn로 표시했지만, 이 PR에서는 위 method들이 `Branded`를 사용하도록 변경함으로써 safe fn으로 바꾸었습니다.
* 이전
```Rust
unsafe fn dup(&self, handle: &Ref<Self::Data>) -> Ref<Self::Data>;
unsafe fn dealloc(&self, handle: Ref<Self::Data>);
pub unsafe fn from_unchecked(arena: &A, inner: Ref<T>) -> Self;
```
* 이후
```Rust
fn dup<'id>(self: …
```
> [Closes #479] Use `Branded` in `Arena`, `Rc`

- kernel-rs/src/console.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/inode.rs
- kernel-rs/src/fs/log.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lock/sleepablelock.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/pipe.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/uart.rs
- kernel-rs/src/virtio/virtio_disk.rs
구체적으론 init 하는 부분을 함수로 만들었습니다. 아직 주석 등을 작성하지 않아서 머지는 못합니다. 참고로 봐주셨으면 합니다.
제 생각에 이 일은 좀더 큰 맥락에서 다음과 같은 일들과 관련이 있습니다.
- `'static` 사용 없애기 #428 , `kernel()` 사용 없애기 #kernel #267 : 이러한 사용은 kernel을 object로 이해하지 못했다는 증거가 됩니다.
- multiarch support #381 : 이 일을 하려면 arch-dependent, arch-independent 파트를 명확히 나눠야 하고, 이를 위해서는 kernel을 좀더 modular하게 object로 이해하는게 필요하리라 생각합니다.
앞으로 #428, #267 의 우선순위를 높여 관심을 기울이면 어떨까 합니다. 큰 디자인 변경사항이다보니 모듈별 개선보다 먼저 이뤄지면 좋겠습니다.
> make kernel more object-like

- kernel-rs/Cargo.lock
- kernel-rs/Cargo.toml
- kernel-rs/src/kernel.rs
- kernel-rs/src/lock/spinlock.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/start.rs
- kernel-rs/src/trap.rs
Closes #440 
- `usertrapret() -> !`이 절대 return하지 않음을 표현함으로써 #440 을 해결하였습니다.
- usertrap/forkret/usertrapret의 관계를 더 깊이 표현하려면 (1) `UserTrapRet` 타입을 `!`을 감싸서 새로 만들고, (2) 앞 3개 함수들이 모두 `UserTrapRet`을 리턴하도록 하는 수도 있겠습니다.... 만 여기까지는 안하는게 더 readability가 높을 것 같습니다.
> usertrapret never returns

- kernel-rs/src/console.rs
- kernel-rs/src/file.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/trap.rs
- kernel-rs/src/uart.rs
`Uart`와 `Console`을 리팩토링하는 PR입니다.
* `Uart`와 `Console`이 상호 의존적이기 때문에 어느 한쪽이 다른 하나를 소유한다고 보기 어려운 것 같아, 구조는 그대로 두고 대부분의 메서드가 `KernelRef`나 `KernelCtx`를 받도록 만들었습니다.
* `Uart`가 MMIO 레지스터를 소유하는 개념을 명확히 했습니다. 여러 `Uart`가 동시에 존재할 수 있으므로, `Uart`는 만들어질 때 MMIO 레지스터의 위치를 인자로 받습니다.
> [Closes #298] Uart & Console refactoring

- kernel-rs/src/lock/remotelock.rs
- kernel-rs/src/proc.rs
Closes #494 
`RemoteLock`에는 다음과 같은 runtime cost가 있습니다.
* `&Lock`을 저장하기 위해, 추가적인 memory를 차지합니다.
* `RemoteLock::get_pin_mut`을 할때 `assert!`을 사용합니다.
`Branded`를 활용해서, 이러한 runtime cost를 safe하게 없애야합니다.
* `RemoteLock`의 runtime cost를 모두 없앴습니다.
* 새로운 `RemoteLock`을 "src/proc.rs"에 적용하기 위해, "src/proc.rs"`를 다음과 같이 변경했습니다.
* `ProcsRef::wait_guard`를 사용하면, `WaitGuard<'id, 's>`를 얻습니다. (`wait_lock`의 guard)
* `ProcRef::get_mut_parent`에 `WaitGuard`를 넣으면, `Proc::parent` field를 mutably dereference할 수 있습니다.
* 단, 당연하지만 `ProcRef`와 `WaitGuard`의 `'id`가 동일해야합니다.
* 추가로, 다음과 같이 바꾸었습니다.
* `ProcGuard<'s>` -> `ProcGuard<'id, 's>`
* `ProcIter<'s>` -> `ProcIter<'id, 's>`
* `&Procs` 대신 `ProcsRef`를 사용하도록 상당 부분을 변경했습니다.
* `&Proc` 대신 `ProcRef`를 사용하도록 상당 부분을 변경했습니다.
* `ProcsMut`를 추가했습니다. 실제로 사용되는 곳은 `ProcsMut::user_proc_init` 한곳 …
> [Closes #494] Make `RemoteLock` zero cost

- kernel-rs/src/console.rs
- kernel-rs/src/cpu.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/lock/mod.rs
- kernel-rs/src/lock/spinlock.rs
- kernel-rs/src/proc.rs
- kernel-rs/src/trap.rs
* `cpu` 모듈을 추가했습니다.
* `Cpu`의 정의를 `proc` 모듈에서 `cpu` 모듈로 옮겼습니다.
* `cpu` 모듈에 `Cpus` 타입과 `CPUS` static variable을 추가하고 `Kernel`의  `cpus` 필드는 없앴습니다.
`HeldInterrupts` 등을 추가해 interrrupt를 다루는 것은 이 PR에서 하지 않고, 추후에 하겠습니다.
> [Closes #478] Separate Cpu from Kernel

- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/ufs/mod.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/proc/procs.rs
- kernel-rs/src/syscall.rs
`UfsTx::drop`의 `kernel_ctx` 호출을 없애기 위해 `UfsTx`가 드롭되면 패닉하도록 만들고 `UfsTx`와 `KernelCtx`를 받아 `end_op`를 호출하는 `UfsTx::end` 메서드를 추가했습니다.
> Remove `kernel_ctx` in `UfsTx::drop`

- kernel-rs/src/console.rs
- kernel-rs/src/hal.rs
- kernel-rs/src/kernel.rs
- kernel-rs/src/proc/procs.rs
- kernel-rs/src/syscall.rs
- kernel-rs/src/trap.rs
커널이 콘솔에 출력할 때는 `&KernelBuilder`가 필요합니다. 이를 명시적으로 드러낼 수 있도록 `println!` 매크로를 없애고 `KernelBuilder::write_fmt` 메서드를 사용하게 바꾸었습니다.
> Remove println! macro

- kernel-rs/src/arch/riscv.rs
- kernel-rs/src/console.rs
- kernel-rs/src/cpu.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/lock/spinlock.rs
- kernel-rs/src/proc/kernel_ctx.rs
- kernel-rs/src/proc/mod.rs
- kernel-rs/src/proc/procs.rs
- kernel-rs/src/trap.rs
* `push_off`를 하면 `HeldInterrupts`가 나옴.
* `pop_off`는 `HeldInterrupts`를 소모.
* `HeldInterrupts`의 존재가 인터럽트가 꺼져 있음을 보장.
* `NonNull<Cpu>`를 가지고 있음.
* 현재 스레드가 실행 중인 CPU에 대한 shared mutable access를 제공.
* `&Cell<Cpu>`와 유사.
* `Cpu`에 대한 참조가 유일함을 보장할 수 없기 때문에 `&mut Cpu` 대신 `CpuMut` 사용
* `current_raw`: raw pointer 제공. CPU에 접근하지 않고 주소 값만 필요할 때 사용됨.
* `current_unchecked`: `CpuMut` 제공. 인터럽트가 꺼져 있으나 `HeldInterrupts`가 없을 때 사용됨.
* `scheduler`에서 사용: `scheduler`는 CPU에 종속되어 있어 다른 CPU로 이동하지 않음.
* `sched`에서 사용: `Spinlock<ProcInfo>`에 `HeldInterrupts`가 들어 있기는 하지만, `Cell`로부터 참조를 얻을 수 없음. `RefCell`을 사용하면 런타임 비용이 발생하고, `HeldInterrupts`를 `acquire`가 내놓게 하면, `SpinlockGuard`를 자동으로 드롭할 수 없게 됨.
* `current`: `CpuMut` 제공. `&HeldInterrupts`가 필요.
* `intr: Cell<MaybeUninit<HeldInterrupts>>` 필드가 추가됨. 크기가 0이므로 런타임 비용 없음.
> Closes #483

- kernel-rs/src/bio.rs
- kernel-rs/src/exec.rs
- kernel-rs/src/file.rs
- kernel-rs/src/fs/mod.rs
- kernel-rs/src/fs/ufs/inode.rs
- kernel-rs/src/fs/ufs/log.rs
- kernel-rs/src/fs/ufs/mod.rs
- kernel-rs/src/lock/sleeplock.rs
- kernel-rs/src/virtio/virtio_disk.rs
Closes #539
`RawSleeplock`이 `acquire`와 `release`할 때 `KernelCtx`를 인자로 받습니다. 이제 `RawSleeplock`이 `RawLock`을 구현하지 않습니다. 이렇게 해도 코드 중복이 많아 보이지는 않습니다.
> Closes #539

- kernel-rs/src/bio.rs
- kernel-rs/src/fs/ufs/inode.rs
- kernel-rs/src/fs/ufs/log.rs
- kernel-rs/src/fs/ufs/mod.rs
- kernel-rs/src/page.rs
- kernel-rs/src/util/mod.rs
- kernel-rs/src/vm.rs
Closes #576
큰 배열을 복사할 때 1B씩 복사하는 대신 8B씩 복사하도록 수정하여 성능 문제를 해결함.
> [Closes #576] Use 8B-copy instead of 1B-copy

- Makefile
`TARGET=arm make qemu` 로 실행 시 shell이 제대로 실행되지 않던 버그를 해결했습니다.
> Fix ARM build bug

- kernel-rs/src/arch/arm/start.rs
- kernel-rs/src/arch/arm/vm.rs
Context is on [commit message](https://github.com/kaist-cp/rv6/commit/eb527afb14f20eef7ccbc78335d6ba322d263852).
Completed to run usertests to check consistency for code.
> Change MAIR_EL1's mem attribute to speed up kvm

- kernel-rs/src/arena/mru_arena.rs
- kernel-rs/src/kalloc.rs
- kernel-rs/src/util/intrusive_list.rs
Closes #596 
* Changed `fn iter_shared_mut` -> `unsafe fn iter_strong_pin_mut_unchecked`
* Removed interior mutability in `ListEntry`
`List`는 `RefCell`이나 tock의 list등과 달리, interior mutability를 꼭 사용해야하는 이유가 없는 것 같아 이를 제거했습니다.
> [Closes #596] Fix `List` (Remove unsoundness, interior mutability)

- bench.py
- kernel-rs/src/arch/arm/asm.rs
- kernel-rs/src/arch/arm/intr/gicv3.rs
- kernel-rs/src/arch/arm/start.rs
Related context:
https://github.com/kaist-cp/rv6/issues/604
https://github.com/kaist-cp/rv6/issues/605
> Kvm support when opt-level > 1

- kernel-rs/src/bio.rs
- kernel-rs/src/fs/lfs/imap.rs
- kernel-rs/src/fs/lfs/inode.rs
- kernel-rs/src/fs/lfs/mod.rs
- kernel-rs/src/fs/lfs/segment.rs
* Added basic synchronization. [2c5ffeb](https://github.com/kaist-cp/rv6/pull/612/commits/2c5ffeb6bff5f1997682ef015aad35a6e56aeef5)
* Fixed bugs in `InodeGuard::bmap_internal`. [1acf937](https://github.com/kaist-cp/rv6/pull/612/commits/1acf9370c716aace27748da2c1d0a26711f4905c)
* Added `SegSumEntry::IndirectMap`. [de1c0d3](https://github.com/kaist-cp/rv6/pull/612/commits/de1c0d3e58ef2c498ea9268d27f010d1a997f0c5)
* and more
-----
Now, only the following usertests seem to **always** fail.
* manywrites
* bigwrite
We need to implement the segment cleaner to fix this.
> Fix Lfs to pass usertests

- kernel-rs/src/arena/array_arena.rs
- kernel-rs/src/arena/mod.rs
- kernel-rs/src/arena/mru_arena.rs
Closes #597 
간단한 PR입니다. `ArenaRc::new`를 unsafe fn으로 변경했습니다.
이유는 [comment](https://github.com/kaist-cp/rv6/issues/597#issue-1131526745)에 적어놨습니다.
-----
추가적으로, 사실 `array_arena.rs`/`mru_arena.rs` 모듈에서 `ArenaRc::new`를 사용하지 않고 직접
```Rust
return ArenaRc {
arena: self.as_pin().get_ref(),
inner: ManuallyDrop::new(entry),
};
```
와 같은 방법을 사용하면 unsafe를 통하지 않고 `ArenaRc`를 만들 수 있습니다.
다만, 제 생각에는 `array_arena.rs`/`mru_arena.rs`에서는 `ArenaRc`의 내부가 visible하지 않도록 하는 게 자연스러울 것 같으므로, 추후 이런 식으로 변경하는 게 좋을 것 같습니다.
> [Closes #597]Mark `ArenaRc::new` as unsafe.

- kernel-rs/src/fs/lfs/imap.rs
- kernel-rs/src/fs/lfs/inode.rs
- kernel-rs/src/fs/lfs/mod.rs
- kernel-rs/src/fs/lfs/segment.rs
- kernel-rs/src/fs/lfs/superblock.rs
- kernel-rs/src/fs/lfs/tx.rs
- kernel-rs/src/fs/mod.rs
Closes #611 
* Implemented checkpointing in `Lfs`
* All usertests except `manywrites` and `bigdir` work. (These fail since we run out of segments)
* usertests that work when we run it individually may not work if we run it in a sequence. (Again, we run out of segments)
> [Closes #611] Implement checkpointing in `Lfs`

- kernel-rs/src/arch/riscv/asm.rs
- kernel-rs/src/arch/riscv/start.rs
Previously, rv6 (riscv) failed to boot when using a newer qemu version.
This PR fixes this by trivially initializing the physical memory protection CSRs.
* Corresponding commit in xv6-riscv : https://github.com/mit-pdos/xv6-riscv/commit/9655f71758003f93294e82926783024a7e4bcdde
* Also see https://github.com/mit-pdos/xv6-riscv/pull/62
* [RISC-V Spec](https://github.com/riscv/riscv-isa-manual/releases/download/Priv-v1.12/riscv-privileged-20211203.pdf) (See Section 3.7.1)
> Fix to boot at newer qemu

- kernel-rs/src/fs/lfs/cleaner.rs
- kernel-rs/src/fs/lfs/inode.rs
- kernel-rs/src/fs/lfs/mod.rs
- kernel-rs/src/fs/lfs/segment.rs
- kernel-rs/src/fs/lfs/tx.rs
- kernel-rs/src/virtio/virtio_disk.rs
- mklfs/lfs.h
- mklfs/mklfs.c
Sprite-lfs, NetBSD-lfs 와 동일하게 rv6-lfs 도 하나의 `Segment`가 여러개의 segment summary block을 가질 수 있도록 수정하였습니다.
* PR #630 이 merge되면, 이제 parital segment write를 할 때도 disk IO request를 하나만 하면 됩니다. (이전에는 이전의 segment summary block을 update해줘야 했으므로 2번이였음)
* `DSegSum` struct에 `magic`와 `size` field를 추가했습니다.
-----
Sprite-lfs 및 NetBSD-lfs와 동일하게, 어느 disk block이 valid한 summary block인지 아닌지는 magic을 이용하여 판별합니다. 다만, 추가적으로
* Sprite-lfs의 경우, 각각의 segment summary가 다음 segment summary를 가리키는 pointer를 저장하도록 하고
* NetBSD-lfs의 경우, magic뿐만 아니라 check sum도 이용하는 반면,
* rv6-lfs의 경우, magic만을 사용합니다.
> Allow a segment to have more than one segment summary block.

- kernel-rs/src/fs/lfs/cleaner.rs
- kernel-rs/src/fs/lfs/mod.rs
- kernel-rs/src/fs/lfs/segment.rs
- kernel-rs/src/fs/lfs/tx.rs
*  Checkpointing을 덜 자주하도록 수정하였습니다.
* 이전에는 거의 sys call이 끝날때마다 했던 반면, 이제는 최소 25개의 segment block을 write한 후에만 checkpointing을 합니다.
* `TxManager::end_op`가 `SegManager`의 lock을 잡지 않고 내부를 access하도록 수정했습니다.
* 어차피 이 동안은 `SegManager`를 access하는 다른 thread가 존재하지 않습니다.
-----
참고로, 이제 여러 최적화를 해서인지 `Lfs`가 `Ufs`보다 성능면에서 좀 더 빠른 것 같습니다. `bigwrite`, `writebig`, `bigfile`와 같은 usertest만 실행했을때, 실행시간이 다음과 같이 나옵니다.
* ufs : Mean=11.037454444294175, Standard Deviation=0.20522410049808243
* lfs : Mean=7.416204286622815, Standard Deviation=0.10157998064059887
다만, 아직 `Lfs`가 완전히 완성된 건 아니긴 합니다.
> Fix `TxManager`

- kernel-rs/src/bio.rs
- kernel-rs/src/fs/lfs/cleaner.rs
- kernel-rs/src/fs/lfs/imap.rs
- kernel-rs/src/fs/lfs/inode.rs
- kernel-rs/src/fs/lfs/mod.rs
- kernel-rs/src/fs/lfs/segment.rs
- kernel-rs/src/fs/lfs/superblock.rs
- kernel-rs/src/fs/ufs/inode.rs
- kernel-rs/src/fs/ufs/log.rs
- kernel-rs/src/fs/ufs/mod.rs
- kernel-rs/src/fs/ufs/superblock.rs
- kernel-rs/src/lib.rs
- kernel-rs/src/virtio/virtio_disk.rs
* b80c9e4 : 불필요한 disk read를 줄였습니다.
* 954bd03 : `BufData`의 내용을 읽을 때 `From`, `TryFrom` 등의 conversion을 이용하도록 수정하였습니다. (`Lfs`에서만 수정)
* 이전 : 
```Rust
let imap_block = unsafe { &*(buf.deref_inner().data.as_ptr() as *const DImapBlock) };
```
* 이후 : 
```Rust
let imap_block: &DImapBlock = (&buf.deref_inner().data).into();
```
* b1b2cda : `BufInner`의 field들을 모두 private으로 변경한 후 `Buf`의 method들을 이용해 접근하도록 수정하였습니다.
> Fix `Buf` related code

- kernel-rs/Cargo.lock
- kernel-rs/Cargo.toml
- kernel-rs/src/bio.rs
- kernel-rs/src/page.rs
- kernel-rs/src/proc/kernel_ctx.rs
- kernel-rs/src/proc/mod.rs
간단한 wrapper types들에 대해서는 `#[derive(Deref)]`를 이용하도록 수정했습니다.
참고 : 다른 wrapper type들의 경우  `#[derive(Deref)]`를 이용해도 compile error는 일어나지 않는 것을 확인했으나, deref Target이 저희가 원하는 것과 조금 달라지게 되어서
(ex: 우리가 원하는 `deref()` 결과 : `&T`, `#[derive(Deref)]`를 이용할 경우의 `deref()` 결과 : `&ManuallyDrop<T>`)
그냥 직접 구현하는 현재 방법을 유지했습니다.
> Use `#[derive(Deref)]` for simple cases
