kernel-rs/src/fs.rs, kernel-rs/src/log.rs
- related to #154 (커밋 메시지 참고)
- all usertests passed
- cargo fmt
=> Remove redundant pub + change variable type (related to #154)

kernel-rs/src/console.rs, kernel-rs/src/fs.rs, kernel-rs/src/kalloc.rs, kernel-rs/src/lib.rs, kernel-rs/src/log.rs, kernel-rs/src/pipe.rs, kernel-rs/src/proc.rs, kernel-rs/src/sysfile.rs, kernel-rs/src/vm.rs
=> [Closes #132] Remove libc::CVoid

kernel-rs/src/proc.rs
=> Make wait channel non-zero-sized

kernel-rs/Cargo.toml, kernel-rs/src/arena.rs, kernel-rs/src/exec.rs, kernel-rs/src/file.rs, kernel-rs/src/fs/inode.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/path.rs, kernel-rs/src/kernel.rs, kernel-rs/src/lib.rs, kernel-rs/src/proc.rs, kernel-rs/src/spinlock.rs, kernel-rs/src/sysfile.rs
=> Inode refactor 20201028

kernel-rs/src/proc.rs
- closes #303 
- CI 통과 후 리뷰 요청 드리겠습니다.
- 상욱님의 코멘트를 참고해 twochildren을 통과하도록 코드를 수정하였습니다. `Waitchannel::wakeup()`이 아닌 `Proc::wakeup()`을 실행한 것이 문제였던 것으로 보입니다.
- travis CI에서 빌드가 오랜 시간 시작되지 않는 이슈는 다른 원인 때문인 것으로 예상하고 있습니다.
- [kimjungwow/rv6 에서 travis CI를 먼저 빌드해보니 통과했습니다.](https://github.com/kaist-cp/rv6/issues/303#issuecomment-741841785)
=> [Closes #303] Hotfix : twochildren usertest will now pass

kernel-rs/src/fs/inode.rs, kernel-rs/src/fs/log.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/virtio_disk.rs
- 이 PR처럼 수정한 이유
- **`Disk::read(), Disk::write()` 형태로 사용하는 것은 어느 `struct Disk`에 대해 read, write하는지 명확히 드러내지 못한다고 판단했습니다.**
- `Disk::read(), write()` 내부에서 `kernel().disk`를 사용하기 때문에 + xv6에서는 한 개의 `struct Disk`만 사용되기 때문에, `struct Kernel` 안에 있는 `struct Disk`에 대해 read write를 하는 것은 맞습니다.
- 하지만 `(&kernel().disk).read()`, `(&kernel().disk).write()` 형태로 사용해야 어떤 Disk에 대해 읽고 쓰는지를 잘 드러낼 수 있다고 생각합니다.
- 비슷한 맥락으로는 `begin_transaction()`이 있습니다. `begin_transaction()`도 `kernel().fs().begin_transaction();` 형태로 호출합니다. ( `begin_transaction()` 내부에서 `kernel().fs()`를 호출하지 않습니다)
- **dependency 제거 #271**
- 이 PR이 적용되면 `log.rs, inode.rs, mod.rs`가 `Disk`를 필요로 하지 않게 됩니다.
- 고민해볼 점
- `kernel()` 호출이 잦아집니다.
- 기존의 `Disk::read(), write()` 내부에서도 `kernel()`을 실행하기 때문에, 관점에 따라 글로벌 함수 `kernel()`을 `Disk::read()`를 실행하기 전에 호출하느냐 …
=> Change Disk::read/write into Sleepablelock<Disk>'s methods (related to #271)

kernel-rs/src/riscv.rs, kernel-rs/src/vm.rs
Closes #341
bitflags를 사용한 구현입니다.
=> [Closes #341] Use bitflags

kernel-rs/src/arena.rs, kernel-rs/src/console.rs, kernel-rs/src/exec.rs, kernel-rs/src/file.rs, kernel-rs/src/fs/inode.rs, kernel-rs/src/fs/log.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/path.rs, kernel-rs/src/kernel.rs, kernel-rs/src/lib.rs, kernel-rs/src/pipe.rs, kernel-rs/src/proc.rs, kernel-rs/src/spinlock.rs, kernel-rs/src/syscall.rs, kernel-rs/src/sysfile.rs, kernel-rs/src/uart.rs, kernel-rs/src/virtio_disk.rs, kernel-rs/src/vm.rs
- code에 적힌 TODO와 issue를 매치했습니다.
- 이미 해결된 TODO나 간단하게 해결할 수 있는 TODO는 해결하고 제거했습니다.
=> Fix TODO documentation

kernel-rs/src/arena.rs, kernel-rs/src/console.rs, kernel-rs/src/file.rs, kernel-rs/src/fs/inode.rs, kernel-rs/src/fs/log.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/path.rs, kernel-rs/src/fs/superblock.rs, kernel-rs/src/kernel.rs, kernel-rs/src/lib.rs, kernel-rs/src/page.rs, kernel-rs/src/pipe.rs, kernel-rs/src/plic.rs, kernel-rs/src/proc.rs, kernel-rs/src/riscv.rs, kernel-rs/src/sleepablelock.rs, kernel-rs/src/sleeplock.rs, kernel-rs/src/spinlock.rs, kernel-rs/src/start.rs, kernel-rs/src/syscall.rs, kernel-rs/src/sysfile.rs, kernel-rs/src/sysproc.rs, kernel-rs/src/trap.rs
- closes #335
- #![feature(unsafe_block_in_unsafe_fn)]를 적용하고 unsafe block들을 추가했습니다.
=> [Closes #335] apply #![feature(unsafe_block_in_unsafe_fn)]

kernel-rs/src/kernel.rs, kernel-rs/src/proc.rs, kernel-rs/src/spinlock.rs
=> [Closes #396] Use UnsafeCell for cpus

kernel-rs/src/proc.rs, kernel-rs/src/sysfile.rs
=> Closes #415

kernel-rs/src/fs/inode.rs
Closes #360 
원래보다 `Dirent` 복사가 더 일어날 수도 있어 보이지만, `Dirent`가 16 bytes밖에 안 되기도 하고 아마 잘 최적화될 것 같기도 합니다.
크게 중요한 이슈는 아니고 원래 코드도 별 문제 없어 보여서 꼭 merge할 필요는 없을 것 같습니다만 일단 PR은 만들어 두겠습니다.
=> Closes #360

kernel-rs/src/file.rs, kernel-rs/src/fs/inode.rs, kernel-rs/src/fs/log.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/kernel.rs, kernel-rs/src/sysfile.rs, kernel-rs/src/trap.rs
Closes #445
기존의 구조를
```
FileSystem - Disk
- Log  - LogData
- &Disk
```
아래와 같이 바꾸었습니다.
```
FileSystem - Log - LogData
- Disk
```
=> Closes #445

kernel-rs/src/proc.rs
`ProcGuard`가 `*const ProcBuilder` 대신 `&ProcBuilder`를 가지고 있게 하고 lifetime parameter를 추가했습니다.
=> Add lifetime parameter to ProcGuard

kernel-rs/src/lock/mod.rs, kernel-rs/src/util/branded.rs
매우 간단한 PR입니다. (주석을 조금 변경했습니다.)
바로 merge해주시면 될 것 같습니다.
=> Fix comments

kernel-rs/src/kernel.rs, kernel-rs/src/proc.rs, kernel-rs/src/util/branded.rs
Closes #498 
말씀해주신대로, `brand`함수에 대한 내용을 주석으로 추가했습니다.
=> [Closes #498] Fix comments.

kernel-rs/Cargo.lock, kernel-rs/Cargo.toml, kernel-rs/src/arena/array_arena.rs, kernel-rs/src/arena/mod.rs, kernel-rs/src/arena/mru_arena.rs, kernel-rs/src/exec.rs, kernel-rs/src/file.rs, kernel-rs/src/lib.rs, kernel-rs/src/lock/mod.rs, kernel-rs/src/lock/sleeplock.rs, kernel-rs/src/page.rs, kernel-rs/src/param.rs, kernel-rs/src/uart.rs, kernel-rs/src/util/mod.rs, kernel-rs/src/virtio/mod.rs, kernel-rs/src/virtio/virtio_disk.rs
=> Remove todos

kernel-rs/src/util/list.rs
=> [Closes #518] In `List`, check whether `T` is `Unpin` or not.

kernel-rs/src/console.rs, kernel-rs/src/cpu.rs, kernel-rs/src/exec.rs, kernel-rs/src/file.rs, kernel-rs/src/hal.rs, kernel-rs/src/kernel.rs, kernel-rs/src/lib.rs, kernel-rs/src/lock/spinlock.rs, kernel-rs/src/pipe.rs, kernel-rs/src/proc/kernel_ctx.rs, kernel-rs/src/proc/mod.rs, kernel-rs/src/proc/procs.rs, kernel-rs/src/syscall.rs, kernel-rs/src/trap.rs
Closes #525
`Hal` 타입을 추가하고 `Console`, `Printer`, `Kmem`, `Cpus`를 넣었습니다.
=> Closes #525: Add `Hal` Type

kernel-rs/src/arena/array_arena.rs, kernel-rs/src/arena/mod.rs, kernel-rs/src/arena/mru_arena.rs, kernel-rs/src/file.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/ufs/mod.rs
=> Closes #502

kernel-rs/src/proc/mod.rs, kernel-rs/src/proc/procs.rs
=> Closes #519

kernel-rs/src/kernel.rs, kernel-rs/src/lock/remotelock.rs, kernel-rs/src/proc/mod.rs, kernel-rs/src/proc/procs.rs
=> Closes #428

kernel-rs/src/file.rs, kernel-rs/src/fs/ufs/inode.rs, kernel-rs/src/kernel.rs, kernel-rs/src/lock/sleeplock.rs, kernel-rs/src/proc/procs.rs
=> Closes #267

kernel-rs/src/kernel.rs
=> Closes #531

kernel-rs/src/fs/ufs/log.rs, kernel-rs/src/fs/ufs/mod.rs
=> Closes #448

kernel-rs/src/arena/array_arena.rs, kernel-rs/src/arena/mod.rs, kernel-rs/src/arena/mru_arena.rs, kernel-rs/src/bio.rs, kernel-rs/src/file.rs, kernel-rs/src/fs/lfs.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/ufs/inode.rs, kernel-rs/src/lock/mod.rs, kernel-rs/src/util/intrusive_list.rs, kernel-rs/src/util/mod.rs, kernel-rs/src/util/rc_cell.rs, kernel-rs/src/util/shared_mut.rs, kernel-rs/src/util/static_arc.rs
=> Use `AtomicUsize` in `RcCell`

README-rv6.md
Add RUST_MODE=release for better performance
=> update doc to include rust_mode param

kernel-rs/src/fs/lfs/inode.rs, kernel-rs/src/fs/lfs/log.rs, kernel-rs/src/fs/lfs/mod.rs, kernel-rs/src/fs/lfs/superblock.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/ufs/inode.rs, kernel-rs/src/fs/ufs/mod.rs
- 코드 양이 길어서 커밋 순서대로 봐주시면 될 것 같습니다.
=> Lfs initialize

kernel-rs/Cargo.lock, kernel-rs/Cargo.toml
=> [Closes #577] Update dependency for bitmaps

kernel-rs/src/fs/lfs/inode.rs, kernel-rs/src/fs/lfs/mod.rs, kernel-rs/src/fs/lfs/segment.rs, kernel-rs/src/fs/lfs/superblock.rs, kernel-rs/src/fs/ufs/inode.rs, kernel-rs/src/param.rs
- Added comments for upcoming updates
=> Implemented LFS: basic structs

kernel-rs/src/bio.rs, kernel-rs/src/fs/lfs/imap.rs, kernel-rs/src/fs/lfs/inode.rs, kernel-rs/src/fs/lfs/mod.rs, kernel-rs/src/fs/lfs/segment.rs, kernel-rs/src/fs/lfs/superblock.rs, kernel-rs/src/param.rs
* Added segment.rs and imap.rs (Probably almost everything are at least functional). To see how they works, see inode.rs as an example.
* inode.rs and mod.rs still needs a lot of changes, but doesn't seem that hard.
=> Implement `Segment`, `Imap`

.gitignore, Makefile, README-rv6.md, kernel-rs/src/fs/lfs/imap.rs, kernel-rs/src/fs/lfs/inode.rs, kernel-rs/src/fs/lfs/mod.rs, kernel-rs/src/fs/lfs/segment.rs, kernel-rs/src/fs/lfs/superblock.rs, kernel-rs/src/param.rs
Booting with lfs now works.
* Most basic user programs (ls, cat, grep, wc, etc.) work fine.
* Reading anything (inode, data) seems to work fine, but trying to write something seems to sometimes causes a problem.
-----
* kernel booting
* kernel main: O
* superblock load: O
* checkpoint load: O
* imap load: O
* inode, data block load: O
* user program init
* exec: O
* run sh: O
* user programs
* cat O
* echo O
* forktest O
* grep O
* init O
* ln ~~X~~ -> O
* ls O
* mkdir ~~X~~ -> O
* rm ~~X~~ -> O
* sh O
* stressfs X
* usertests X
* most tests not related to fs seem to work
* grind X
* wc O
* zombie O
* hello O
To run, do
```
make clean
FS=lfs CPUS=1 make qemu
```
=> Make lfs bootable

kernel-rs/src/file.rs, kernel-rs/src/fs/lfs/cleaner.rs, kernel-rs/src/fs/lfs/imap.rs, kernel-rs/src/fs/lfs/inode.rs, kernel-rs/src/fs/lfs/mod.rs, kernel-rs/src/fs/lfs/segment.rs, kernel-rs/src/fs/lfs/tx.rs, kernel-rs/src/fs/mod.rs, kernel-rs/src/fs/ufs/mod.rs, kernel-rs/src/virtio/virtio_disk.rs, mklfs/lfs.h, mklfs/mklfs.c
Closes #614 
* Implemented the segment cleaner. Now, **lfs passes all usertests**.
* Note: Only implemented basic functionality in this PR. We may want to choose a better way to select segments and when to run the cleaner.
=> [Closes #614] Implement the segment cleaner

kernel-rs/src/virtio/virtio_disk.rs
Lfs가 sequential disk write를 더 효율적으로 수행하도록 수정하였습니다.
* 여러가지 방법을 실험해봤는데, 지금처럼 disk IO request를 하나만 하도록 하는 방법이 가장 빠른 것 같습니다.
* 수정 전 : Mean=65.92483518831432
* 수정 후 : Mean=55.13753894902766
* (segment를 commit할때, disk write를 여러 번 반복하도록 하면서 수행시간을 측정해봤습니다.)
=> Fix `VirtioDisk::write_seq` to use a single descriptor set.

kernel-rs/src/fs/lfs/cleaner.rs, kernel-rs/src/fs/lfs/mod.rs, kernel-rs/src/fs/lfs/tx.rs, kernel-rs/src/param.rs
cleaner가 실행되는 도중 crash가 일어나도 consistency를 유지할 수 있도록 수정하였습니다.
=> Fix cleaner
